// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/base.proto

package app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DefaultRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultRes) Reset()         { *m = DefaultRes{} }
func (m *DefaultRes) String() string { return proto.CompactTextString(m) }
func (*DefaultRes) ProtoMessage()    {}
func (*DefaultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7751bee5297d00d, []int{0}
}

func (m *DefaultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultRes.Unmarshal(m, b)
}
func (m *DefaultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultRes.Marshal(b, m, deterministic)
}
func (m *DefaultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultRes.Merge(m, src)
}
func (m *DefaultRes) XXX_Size() int {
	return xxx_messageInfo_DefaultRes.Size(m)
}
func (m *DefaultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultRes.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultRes proto.InternalMessageInfo

func (m *DefaultRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DefaultRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DefaultRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7751bee5297d00d, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DefaultRes)(nil), "app.defaultRes")
	proto.RegisterType((*Empty)(nil), "app.empty")
}

func init() { proto.RegisterFile("app/base.proto", fileDescriptor_e7751bee5297d00d) }

var fileDescriptor_e7751bee5297d00d = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2c, 0x28, 0xd0,
	0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0x28, 0x50,
	0x72, 0xe3, 0xe2, 0x4a, 0x49, 0x4d, 0x4b, 0x2c, 0xcd, 0x29, 0x09, 0x4a, 0x2d, 0x16, 0x12, 0xe2,
	0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x85, 0x04,
	0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0xaa,
	0x94, 0xc4, 0x92, 0x44, 0x09, 0x66, 0xb0, 0x10, 0x98, 0xad, 0xc4, 0xce, 0xc5, 0x9a, 0x9a, 0x5b,
	0x50, 0x52, 0xe9, 0x24, 0x18, 0xc5, 0xaf, 0xa7, 0x0f, 0xb6, 0x40, 0x3f, 0xb1, 0xa0, 0xc0, 0x3a,
	0xb1, 0xa0, 0x20, 0x89, 0x0d, 0xcc, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x0a, 0xe4,
	0xa5, 0x81, 0x00, 0x00, 0x00,
}
