// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/company.proto

package app

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompanyAppInfo struct {
	// @inject_tag: json:"id"
	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// @inject_tag: binding:"required" json:"app_name"
	AppName string `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	// @inject_tag:  json:"version"
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// @inject_tag:  json:"img"
	Img string `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	// @inject_tag:  json:"icon"
	Icon string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	//@inject_tag: json:"desc"
	Desc string `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	//@inject_tag: json:"open_time"
	OpenTime string `protobuf:"bytes,7,opt,name=openTime,proto3" json:"openTime,omitempty"`
	//@inject_tag: json:"expired_at"
	ExpiredAt            string   `protobuf:"bytes,8,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompanyAppInfo) Reset()         { *m = CompanyAppInfo{} }
func (m *CompanyAppInfo) String() string { return proto.CompactTextString(m) }
func (*CompanyAppInfo) ProtoMessage()    {}
func (*CompanyAppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{0}
}

func (m *CompanyAppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyAppInfo.Unmarshal(m, b)
}
func (m *CompanyAppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyAppInfo.Marshal(b, m, deterministic)
}
func (m *CompanyAppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyAppInfo.Merge(m, src)
}
func (m *CompanyAppInfo) XXX_Size() int {
	return xxx_messageInfo_CompanyAppInfo.Size(m)
}
func (m *CompanyAppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyAppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyAppInfo proto.InternalMessageInfo

func (m *CompanyAppInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CompanyAppInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *CompanyAppInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CompanyAppInfo) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *CompanyAppInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *CompanyAppInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CompanyAppInfo) GetOpenTime() string {
	if m != nil {
		return m.OpenTime
	}
	return ""
}

func (m *CompanyAppInfo) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

type CompanyModuleInfo struct {
	// @inject_tag: binding:"required,min=1"  json:"app_id"
	AppID int32 `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`
	// @inject_tag:  json:"id"
	ID int32 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// @inject_tag: binding:"required"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	//@inject_tag: json:"icon" binding:"required"
	Icon string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	//@inject_tag: json:"price" binding:"min=0"
	Price float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	// @inject_tag: binding:"required,min=0,max=5" json:"unit"
	Unit int32 `protobuf:"varint,7,opt,name=unit,proto3" json:"unit,omitempty"`
	// @inject_tag: binding:"required,min=0,max=2" json:"type"
	Type int32 `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	//@inject_tag: json:"desc"
	Desc string `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	//@inject_tag: json:"app_name"
	AppName string `protobuf:"bytes,10,opt,name=appName,proto3" json:"appName,omitempty"`
	//@inject_tag: json:"open_time"
	OpenTime string `protobuf:"bytes,11,opt,name=openTime,proto3" json:"openTime,omitempty"`
	//@inject_tag: json:"expired_at"
	ExpiredAt            string   `protobuf:"bytes,12,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompanyModuleInfo) Reset()         { *m = CompanyModuleInfo{} }
func (m *CompanyModuleInfo) String() string { return proto.CompactTextString(m) }
func (*CompanyModuleInfo) ProtoMessage()    {}
func (*CompanyModuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{1}
}

func (m *CompanyModuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyModuleInfo.Unmarshal(m, b)
}
func (m *CompanyModuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyModuleInfo.Marshal(b, m, deterministic)
}
func (m *CompanyModuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyModuleInfo.Merge(m, src)
}
func (m *CompanyModuleInfo) XXX_Size() int {
	return xxx_messageInfo_CompanyModuleInfo.Size(m)
}
func (m *CompanyModuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyModuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyModuleInfo proto.InternalMessageInfo

func (m *CompanyModuleInfo) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *CompanyModuleInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CompanyModuleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompanyModuleInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CompanyModuleInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *CompanyModuleInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CompanyModuleInfo) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *CompanyModuleInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CompanyModuleInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CompanyModuleInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *CompanyModuleInfo) GetOpenTime() string {
	if m != nil {
		return m.OpenTime
	}
	return ""
}

func (m *CompanyModuleInfo) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

type CompanyInitReq struct {
	//@inject_tag: json:"company_id" binding:"required"
	CompanyID            int32    `protobuf:"varint,1,opt,name=companyID,proto3" json:"companyID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompanyInitReq) Reset()         { *m = CompanyInitReq{} }
func (m *CompanyInitReq) String() string { return proto.CompactTextString(m) }
func (*CompanyInitReq) ProtoMessage()    {}
func (*CompanyInitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{2}
}

func (m *CompanyInitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyInitReq.Unmarshal(m, b)
}
func (m *CompanyInitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyInitReq.Marshal(b, m, deterministic)
}
func (m *CompanyInitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyInitReq.Merge(m, src)
}
func (m *CompanyInitReq) XXX_Size() int {
	return xxx_messageInfo_CompanyInitReq.Size(m)
}
func (m *CompanyInitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyInitReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyInitReq proto.InternalMessageInfo

func (m *CompanyInitReq) GetCompanyID() int32 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

type OpenReq struct {
	//@inject_tag: json:"object_type" binding:"required"
	ObjectType int32 `protobuf:"varint,1,opt,name=ObjectType,proto3" json:"ObjectType,omitempty"`
	//@inject_tag: json:"object_id"
	ObjectID             int32    `protobuf:"varint,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenReq) Reset()         { *m = OpenReq{} }
func (m *OpenReq) String() string { return proto.CompactTextString(m) }
func (*OpenReq) ProtoMessage()    {}
func (*OpenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{3}
}

func (m *OpenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenReq.Unmarshal(m, b)
}
func (m *OpenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenReq.Marshal(b, m, deterministic)
}
func (m *OpenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenReq.Merge(m, src)
}
func (m *OpenReq) XXX_Size() int {
	return xxx_messageInfo_OpenReq.Size(m)
}
func (m *OpenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenReq.DiscardUnknown(m)
}

var xxx_messageInfo_OpenReq proto.InternalMessageInfo

func (m *OpenReq) GetObjectType() int32 {
	if m != nil {
		return m.ObjectType
	}
	return 0
}

func (m *OpenReq) GetObjectID() int32 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *OpenReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type CompanyAppListReq struct {
	//@inject_tag: json:"app_name"
	AppName string `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	//@inject_tag: form:"page_size"
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//@inject_tag: form:"page"
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompanyAppListReq) Reset()         { *m = CompanyAppListReq{} }
func (m *CompanyAppListReq) String() string { return proto.CompactTextString(m) }
func (*CompanyAppListReq) ProtoMessage()    {}
func (*CompanyAppListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{4}
}

func (m *CompanyAppListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyAppListReq.Unmarshal(m, b)
}
func (m *CompanyAppListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyAppListReq.Marshal(b, m, deterministic)
}
func (m *CompanyAppListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyAppListReq.Merge(m, src)
}
func (m *CompanyAppListReq) XXX_Size() int {
	return xxx_messageInfo_CompanyAppListReq.Size(m)
}
func (m *CompanyAppListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyAppListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyAppListReq proto.InternalMessageInfo

func (m *CompanyAppListReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *CompanyAppListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CompanyAppListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CompanyAppListData struct {
	List                 []*CompanyAppInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                int32             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CompanyAppListData) Reset()         { *m = CompanyAppListData{} }
func (m *CompanyAppListData) String() string { return proto.CompactTextString(m) }
func (*CompanyAppListData) ProtoMessage()    {}
func (*CompanyAppListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{5}
}

func (m *CompanyAppListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyAppListData.Unmarshal(m, b)
}
func (m *CompanyAppListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyAppListData.Marshal(b, m, deterministic)
}
func (m *CompanyAppListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyAppListData.Merge(m, src)
}
func (m *CompanyAppListData) XXX_Size() int {
	return xxx_messageInfo_CompanyAppListData.Size(m)
}
func (m *CompanyAppListData) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyAppListData.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyAppListData proto.InternalMessageInfo

func (m *CompanyAppListData) GetList() []*CompanyAppInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CompanyAppListData) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CompanyAppListRes struct {
	Code                 int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *CompanyAppListData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CompanyAppListRes) Reset()         { *m = CompanyAppListRes{} }
func (m *CompanyAppListRes) String() string { return proto.CompactTextString(m) }
func (*CompanyAppListRes) ProtoMessage()    {}
func (*CompanyAppListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{6}
}

func (m *CompanyAppListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyAppListRes.Unmarshal(m, b)
}
func (m *CompanyAppListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyAppListRes.Marshal(b, m, deterministic)
}
func (m *CompanyAppListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyAppListRes.Merge(m, src)
}
func (m *CompanyAppListRes) XXX_Size() int {
	return xxx_messageInfo_CompanyAppListRes.Size(m)
}
func (m *CompanyAppListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyAppListRes.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyAppListRes proto.InternalMessageInfo

func (m *CompanyAppListRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CompanyAppListRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CompanyAppListRes) GetData() *CompanyAppListData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CompanyModuleListReq struct {
	//@inject_tag: json:"form"
	AppID int32 `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`
	//@inject_tag: form:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//@inject_tag: form:"page_size"
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//@inject_tag: form:"page"
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompanyModuleListReq) Reset()         { *m = CompanyModuleListReq{} }
func (m *CompanyModuleListReq) String() string { return proto.CompactTextString(m) }
func (*CompanyModuleListReq) ProtoMessage()    {}
func (*CompanyModuleListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{7}
}

func (m *CompanyModuleListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyModuleListReq.Unmarshal(m, b)
}
func (m *CompanyModuleListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyModuleListReq.Marshal(b, m, deterministic)
}
func (m *CompanyModuleListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyModuleListReq.Merge(m, src)
}
func (m *CompanyModuleListReq) XXX_Size() int {
	return xxx_messageInfo_CompanyModuleListReq.Size(m)
}
func (m *CompanyModuleListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyModuleListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyModuleListReq proto.InternalMessageInfo

func (m *CompanyModuleListReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *CompanyModuleListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompanyModuleListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CompanyModuleListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CompanyModuleListData struct {
	//@inject_tag: json:"list"
	List []*CompanyModuleInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	//@inject_tag: json:"total"
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompanyModuleListData) Reset()         { *m = CompanyModuleListData{} }
func (m *CompanyModuleListData) String() string { return proto.CompactTextString(m) }
func (*CompanyModuleListData) ProtoMessage()    {}
func (*CompanyModuleListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{8}
}

func (m *CompanyModuleListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyModuleListData.Unmarshal(m, b)
}
func (m *CompanyModuleListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyModuleListData.Marshal(b, m, deterministic)
}
func (m *CompanyModuleListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyModuleListData.Merge(m, src)
}
func (m *CompanyModuleListData) XXX_Size() int {
	return xxx_messageInfo_CompanyModuleListData.Size(m)
}
func (m *CompanyModuleListData) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyModuleListData.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyModuleListData proto.InternalMessageInfo

func (m *CompanyModuleListData) GetList() []*CompanyModuleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CompanyModuleListData) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CompanyModuleListRes struct {
	//@inject_tag: json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	//@inject_tag: json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	//@inject_tag: json:"data"
	Data                 *CompanyModuleListData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CompanyModuleListRes) Reset()         { *m = CompanyModuleListRes{} }
func (m *CompanyModuleListRes) String() string { return proto.CompactTextString(m) }
func (*CompanyModuleListRes) ProtoMessage()    {}
func (*CompanyModuleListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfdb04e1824999b, []int{9}
}

func (m *CompanyModuleListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompanyModuleListRes.Unmarshal(m, b)
}
func (m *CompanyModuleListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompanyModuleListRes.Marshal(b, m, deterministic)
}
func (m *CompanyModuleListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompanyModuleListRes.Merge(m, src)
}
func (m *CompanyModuleListRes) XXX_Size() int {
	return xxx_messageInfo_CompanyModuleListRes.Size(m)
}
func (m *CompanyModuleListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CompanyModuleListRes.DiscardUnknown(m)
}

var xxx_messageInfo_CompanyModuleListRes proto.InternalMessageInfo

func (m *CompanyModuleListRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CompanyModuleListRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CompanyModuleListRes) GetData() *CompanyModuleListData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CompanyAppInfo)(nil), "app.CompanyAppInfo")
	proto.RegisterType((*CompanyModuleInfo)(nil), "app.CompanyModuleInfo")
	proto.RegisterType((*CompanyInitReq)(nil), "app.companyInitReq")
	proto.RegisterType((*OpenReq)(nil), "app.openReq")
	proto.RegisterType((*CompanyAppListReq)(nil), "app.companyAppListReq")
	proto.RegisterType((*CompanyAppListData)(nil), "app.companyAppListData")
	proto.RegisterType((*CompanyAppListRes)(nil), "app.companyAppListRes")
	proto.RegisterType((*CompanyModuleListReq)(nil), "app.companyModuleListReq")
	proto.RegisterType((*CompanyModuleListData)(nil), "app.companyModuleListData")
	proto.RegisterType((*CompanyModuleListRes)(nil), "app.companyModuleListRes")
}

func init() { proto.RegisterFile("app/company.proto", fileDescriptor_9bfdb04e1824999b) }

var fileDescriptor_9bfdb04e1824999b = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xff, 0x9a, 0x76, 0x5a, 0xa5, 0xcd, 0xb6, 0x14, 0x13, 0x21, 0x14, 0x59, 0x42, 0x44,
	0x80, 0x1c, 0x29, 0x9c, 0x10, 0xa7, 0x96, 0x5c, 0x22, 0x01, 0x95, 0xdc, 0x5e, 0x8a, 0xc4, 0x61,
	0x63, 0x6f, 0x22, 0xa3, 0xc4, 0x1e, 0x62, 0x07, 0x51, 0x5e, 0x85, 0x17, 0xe2, 0x25, 0x78, 0x17,
	0xb4, 0xb3, 0x6b, 0x67, 0x4d, 0xdc, 0x8a, 0xdb, 0xcc, 0x37, 0xe3, 0xd9, 0xf9, 0xbe, 0xfd, 0xd6,
	0xd0, 0xe3, 0x88, 0xa3, 0x38, 0x5f, 0x21, 0xcf, 0xee, 0x42, 0x5c, 0xe7, 0x65, 0xce, 0x1c, 0x8e,
	0xd8, 0xef, 0x4a, 0x7c, 0xc6, 0x0b, 0xa1, 0xc0, 0xe0, 0xb7, 0x05, 0xdd, 0xf7, 0xaa, 0xed, 0x02,
	0x71, 0x9a, 0xcd, 0x73, 0xd6, 0x05, 0x7b, 0x3a, 0xf1, 0xad, 0x81, 0x35, 0xf4, 0x22, 0x7b, 0x3a,
	0x61, 0x3e, 0x74, 0x38, 0xe2, 0x27, 0xbe, 0x12, 0xbe, 0x3d, 0xb0, 0x86, 0x07, 0x51, 0x95, 0xca,
	0xca, 0x77, 0xb1, 0x2e, 0xd2, 0x3c, 0xf3, 0x1d, 0x55, 0xd1, 0x29, 0x3b, 0x01, 0x27, 0x5d, 0x2d,
	0x7c, 0x97, 0x50, 0x19, 0x32, 0x06, 0x6e, 0x1a, 0xe7, 0x99, 0xef, 0x11, 0x44, 0xb1, 0xc4, 0x12,
	0x51, 0xc4, 0xfe, 0x9e, 0xc2, 0x64, 0xcc, 0xfa, 0xb0, 0x9f, 0xa3, 0xc8, 0x6e, 0xd2, 0x95, 0xf0,
	0x3b, 0x84, 0xd7, 0x39, 0x7b, 0x0a, 0x07, 0xe2, 0x07, 0xa6, 0x6b, 0x91, 0x5c, 0x94, 0xfe, 0x3e,
	0x15, 0xb7, 0x40, 0xf0, 0xcb, 0x86, 0x9e, 0xa6, 0xf2, 0x31, 0x4f, 0x36, 0x4b, 0x41, 0x6c, 0xce,
	0xc0, 0xe3, 0x88, 0x35, 0x21, 0x95, 0x68, 0x8e, 0x76, 0xcd, 0x91, 0x81, 0x9b, 0x49, 0x82, 0x8a,
	0x06, 0xc5, 0x12, 0x8b, 0xf3, 0x44, 0x68, 0x12, 0x14, 0xb7, 0xb2, 0x38, 0x03, 0x0f, 0xd7, 0x69,
	0x2c, 0x88, 0x86, 0x15, 0xa9, 0x44, 0x76, 0x6e, 0xb2, 0xb4, 0x24, 0x0e, 0x5e, 0x44, 0xb1, 0xc4,
	0xca, 0x3b, 0x14, 0xb4, 0xba, 0x17, 0x51, 0x5c, 0x6b, 0x70, 0x60, 0x68, 0x60, 0x28, 0x0e, 0x4d,
	0xc5, 0x4d, 0x75, 0x0e, 0x1f, 0x52, 0xe7, 0xe8, 0x5f, 0x75, 0x42, 0xe8, 0x6a, 0x3b, 0x4c, 0xb3,
	0xb4, 0x8c, 0xc4, 0x37, 0xd9, 0x5f, 0x21, 0x95, 0x3a, 0x5b, 0x20, 0xb8, 0x85, 0x8e, 0x9c, 0x2c,
	0x1b, 0x9f, 0x01, 0x5c, 0xcd, 0xbe, 0x8a, 0xb8, 0xbc, 0x91, 0xcb, 0xab, 0x4e, 0x03, 0x91, 0x4b,
	0xa9, 0xac, 0x96, 0xb4, 0xce, 0x6b, 0xca, 0xce, 0x96, 0x72, 0xf0, 0x05, 0x7a, 0x71, 0x6d, 0xb9,
	0x0f, 0x69, 0x41, 0xdb, 0x18, 0x9c, 0xad, 0x1d, 0xce, 0xc8, 0x17, 0xe2, 0x3a, 0xfd, 0x29, 0xaa,
	0xf1, 0x55, 0x2e, 0xc7, 0xcb, 0xb8, 0x1a, 0x2f, 0xe3, 0xe0, 0x1a, 0x58, 0x73, 0xfc, 0x84, 0x97,
	0x9c, 0xbd, 0x00, 0x77, 0x99, 0x16, 0xa5, 0x6f, 0x0d, 0x9c, 0xe1, 0xe1, 0xf8, 0x34, 0xe4, 0x88,
	0x61, 0xd3, 0xf8, 0x11, 0x35, 0xc8, 0xeb, 0x2c, 0xf3, 0x92, 0x2f, 0xf5, 0x59, 0x2a, 0x09, 0xe6,
	0xbb, 0x3b, 0x17, 0xb5, 0x43, 0x94, 0x24, 0xca, 0x21, 0x27, 0xe0, 0xac, 0x8a, 0x85, 0x7e, 0x29,
	0x32, 0x64, 0xaf, 0xc0, 0x4d, 0x78, 0xc9, 0x69, 0xc7, 0xc3, 0xf1, 0x63, 0x3a, 0x79, 0x77, 0xc1,
	0x88, 0x9a, 0x02, 0x84, 0xb3, 0xd8, 0xf4, 0x70, 0x25, 0x4f, 0xbb, 0x8d, 0x2b, 0xdb, 0xda, 0x86,
	0x6d, 0x4d, 0xb9, 0x9c, 0x7b, 0xe4, 0x72, 0x0d, 0xb9, 0x6e, 0xe1, 0xd1, 0xce, 0x89, 0xa4, 0xd8,
	0xcb, 0x86, 0x62, 0xe7, 0xa6, 0x62, 0xdb, 0xf7, 0xf5, 0xa0, 0x68, 0xcb, 0x56, 0x32, 0xff, 0xab,
	0x5b, 0xd8, 0xd0, 0xad, 0x6f, 0xea, 0xd6, 0xdc, 0x54, 0x49, 0x37, 0xfe, 0x63, 0x41, 0x47, 0xd7,
	0xd9, 0x6b, 0x70, 0xa5, 0xcd, 0xd9, 0xa9, 0xf9, 0x95, 0x36, 0x7e, 0xff, 0x98, 0xc0, 0x44, 0xcc,
	0xf9, 0x66, 0x49, 0xfb, 0x3c, 0x07, 0xf7, 0x0a, 0x45, 0xc6, 0x8e, 0xa8, 0xa0, 0x6d, 0xbf, 0xdb,
	0xf6, 0x16, 0x3a, 0xfa, 0xc2, 0xd8, 0x79, 0xcb, 0x2d, 0xca, 0x6f, 0xda, 0xf1, 0x82, 0x5d, 0x02,
	0x6c, 0x77, 0x66, 0x4f, 0xda, 0xb9, 0xc8, 0x01, 0xf7, 0x96, 0x8a, 0xcb, 0xde, 0xe7, 0xe3, 0x70,
	0x44, 0x7f, 0xed, 0x11, 0x47, 0x7c, 0xc7, 0x11, 0x67, 0x7b, 0x94, 0xbe, 0xf9, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0x63, 0xfc, 0xfa, 0xee, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CompanyClient is the client API for Company service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompanyClient interface {
	Init(ctx context.Context, in *CompanyInitReq, opts ...grpc.CallOption) (*DefaultRes, error)
	Open(ctx context.Context, in *OpenReq, opts ...grpc.CallOption) (*DefaultRes, error)
	// 机构app列表
	AppList(ctx context.Context, in *CompanyAppListReq, opts ...grpc.CallOption) (*CompanyAppListRes, error)
	//module列表
	ModuleList(ctx context.Context, in *CompanyModuleListReq, opts ...grpc.CallOption) (*CompanyModuleListRes, error)
}

type companyClient struct {
	cc *grpc.ClientConn
}

func NewCompanyClient(cc *grpc.ClientConn) CompanyClient {
	return &companyClient{cc}
}

func (c *companyClient) Init(ctx context.Context, in *CompanyInitReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/app.company/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) Open(ctx context.Context, in *OpenReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/app.company/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) AppList(ctx context.Context, in *CompanyAppListReq, opts ...grpc.CallOption) (*CompanyAppListRes, error) {
	out := new(CompanyAppListRes)
	err := c.cc.Invoke(ctx, "/app.company/AppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyClient) ModuleList(ctx context.Context, in *CompanyModuleListReq, opts ...grpc.CallOption) (*CompanyModuleListRes, error) {
	out := new(CompanyModuleListRes)
	err := c.cc.Invoke(ctx, "/app.company/ModuleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyServer is the server API for Company service.
type CompanyServer interface {
	Init(context.Context, *CompanyInitReq) (*DefaultRes, error)
	Open(context.Context, *OpenReq) (*DefaultRes, error)
	// 机构app列表
	AppList(context.Context, *CompanyAppListReq) (*CompanyAppListRes, error)
	//module列表
	ModuleList(context.Context, *CompanyModuleListReq) (*CompanyModuleListRes, error)
}

// UnimplementedCompanyServer can be embedded to have forward compatible implementations.
type UnimplementedCompanyServer struct {
}

func (*UnimplementedCompanyServer) Init(ctx context.Context, req *CompanyInitReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedCompanyServer) Open(ctx context.Context, req *OpenReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (*UnimplementedCompanyServer) AppList(ctx context.Context, req *CompanyAppListReq) (*CompanyAppListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppList not implemented")
}
func (*UnimplementedCompanyServer) ModuleList(ctx context.Context, req *CompanyModuleListReq) (*CompanyModuleListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModuleList not implemented")
}

func RegisterCompanyServer(s *grpc.Server, srv CompanyServer) {
	s.RegisterService(&_Company_serviceDesc, srv)
}

func _Company_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyInitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.company/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).Init(ctx, req.(*CompanyInitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.company/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).Open(ctx, req.(*OpenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyAppListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.company/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).AppList(ctx, req.(*CompanyAppListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Company_ModuleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyModuleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).ModuleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.company/ModuleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).ModuleList(ctx, req.(*CompanyModuleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Company_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.company",
	HandlerType: (*CompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Company_Init_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _Company_Open_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _Company_AppList_Handler,
		},
		{
			MethodName: "ModuleList",
			Handler:    _Company_ModuleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/company.proto",
}
