// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/module.proto

package app

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModuleInfo struct {
	// @inject_tag: binding:"required,min=1"  json:"app_id"
	AppID int32 `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`
	// @inject_tag:  json:"id"
	ID int32 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// @inject_tag: binding:"required"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	//@inject_tag: json:"icon" binding:"required"
	Icon string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	//@inject_tag: json:"price" binding:"min=0"
	Price float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	// @inject_tag: binding:"required,min=0,max=5" json:"unit"
	Unit int32 `protobuf:"varint,7,opt,name=unit,proto3" json:"unit,omitempty"`
	// @inject_tag: binding:"required,min=0,max=2" json:"type"
	Type int32 `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	//@inject_tag: json:"desc"
	Desc string `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	//@inject_tag: json:"content"
	Content string `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	//@inject_tag: json:"created_at,omitempty"
	CreatedAt string `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	//@inject_tag: json:"updated_at"
	UpdatedAt string `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	//@inject_tag: json:"app_name"
	AppName              string   `protobuf:"bytes,13,opt,name=appName,proto3" json:"appName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleInfo) Reset()         { *m = ModuleInfo{} }
func (m *ModuleInfo) String() string { return proto.CompactTextString(m) }
func (*ModuleInfo) ProtoMessage()    {}
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{0}
}

func (m *ModuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleInfo.Unmarshal(m, b)
}
func (m *ModuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleInfo.Marshal(b, m, deterministic)
}
func (m *ModuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleInfo.Merge(m, src)
}
func (m *ModuleInfo) XXX_Size() int {
	return xxx_messageInfo_ModuleInfo.Size(m)
}
func (m *ModuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleInfo proto.InternalMessageInfo

func (m *ModuleInfo) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *ModuleInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ModuleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ModuleInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *ModuleInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ModuleInfo) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *ModuleInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ModuleInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ModuleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ModuleInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ModuleInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ModuleInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type ModuleCreateReq struct {
	Data                 *ModuleInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ModuleCreateReq) Reset()         { *m = ModuleCreateReq{} }
func (m *ModuleCreateReq) String() string { return proto.CompactTextString(m) }
func (*ModuleCreateReq) ProtoMessage()    {}
func (*ModuleCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{1}
}

func (m *ModuleCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleCreateReq.Unmarshal(m, b)
}
func (m *ModuleCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleCreateReq.Marshal(b, m, deterministic)
}
func (m *ModuleCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleCreateReq.Merge(m, src)
}
func (m *ModuleCreateReq) XXX_Size() int {
	return xxx_messageInfo_ModuleCreateReq.Size(m)
}
func (m *ModuleCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleCreateReq proto.InternalMessageInfo

func (m *ModuleCreateReq) GetData() *ModuleInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ModuleUpdateReq struct {
	ModuleID             int32       `protobuf:"varint,1,opt,name=moduleID,proto3" json:"moduleID,omitempty"`
	Data                 *ModuleInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ModuleUpdateReq) Reset()         { *m = ModuleUpdateReq{} }
func (m *ModuleUpdateReq) String() string { return proto.CompactTextString(m) }
func (*ModuleUpdateReq) ProtoMessage()    {}
func (*ModuleUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{2}
}

func (m *ModuleUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleUpdateReq.Unmarshal(m, b)
}
func (m *ModuleUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleUpdateReq.Marshal(b, m, deterministic)
}
func (m *ModuleUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleUpdateReq.Merge(m, src)
}
func (m *ModuleUpdateReq) XXX_Size() int {
	return xxx_messageInfo_ModuleUpdateReq.Size(m)
}
func (m *ModuleUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleUpdateReq proto.InternalMessageInfo

func (m *ModuleUpdateReq) GetModuleID() int32 {
	if m != nil {
		return m.ModuleID
	}
	return 0
}

func (m *ModuleUpdateReq) GetData() *ModuleInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ModuleListReq struct {
	//@inject_tag: form:"app_id"
	AppID int32 `protobuf:"varint,1,opt,name=appID,proto3" json:"appID,omitempty"`
	//@inject_tag: form:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//@inject_tag: form:"page_size"
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	//@inject_tag: form:"page"
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleListReq) Reset()         { *m = ModuleListReq{} }
func (m *ModuleListReq) String() string { return proto.CompactTextString(m) }
func (*ModuleListReq) ProtoMessage()    {}
func (*ModuleListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{3}
}

func (m *ModuleListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleListReq.Unmarshal(m, b)
}
func (m *ModuleListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleListReq.Marshal(b, m, deterministic)
}
func (m *ModuleListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleListReq.Merge(m, src)
}
func (m *ModuleListReq) XXX_Size() int {
	return xxx_messageInfo_ModuleListReq.Size(m)
}
func (m *ModuleListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleListReq proto.InternalMessageInfo

func (m *ModuleListReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *ModuleListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ModuleListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ModuleListData struct {
	//@inject_tag: json:"total"
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	//@inject_tag: json:"list"
	List                 []*ModuleInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ModuleListData) Reset()         { *m = ModuleListData{} }
func (m *ModuleListData) String() string { return proto.CompactTextString(m) }
func (*ModuleListData) ProtoMessage()    {}
func (*ModuleListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{4}
}

func (m *ModuleListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleListData.Unmarshal(m, b)
}
func (m *ModuleListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleListData.Marshal(b, m, deterministic)
}
func (m *ModuleListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleListData.Merge(m, src)
}
func (m *ModuleListData) XXX_Size() int {
	return xxx_messageInfo_ModuleListData.Size(m)
}
func (m *ModuleListData) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleListData.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleListData proto.InternalMessageInfo

func (m *ModuleListData) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ModuleListData) GetList() []*ModuleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ModuleListRes struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ModuleListData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ModuleListRes) Reset()         { *m = ModuleListRes{} }
func (m *ModuleListRes) String() string { return proto.CompactTextString(m) }
func (*ModuleListRes) ProtoMessage()    {}
func (*ModuleListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{5}
}

func (m *ModuleListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleListRes.Unmarshal(m, b)
}
func (m *ModuleListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleListRes.Marshal(b, m, deterministic)
}
func (m *ModuleListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleListRes.Merge(m, src)
}
func (m *ModuleListRes) XXX_Size() int {
	return xxx_messageInfo_ModuleListRes.Size(m)
}
func (m *ModuleListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleListRes.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleListRes proto.InternalMessageInfo

func (m *ModuleListRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModuleListRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ModuleListRes) GetData() *ModuleListData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ModuleDeleteReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleDeleteReq) Reset()         { *m = ModuleDeleteReq{} }
func (m *ModuleDeleteReq) String() string { return proto.CompactTextString(m) }
func (*ModuleDeleteReq) ProtoMessage()    {}
func (*ModuleDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{6}
}

func (m *ModuleDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleDeleteReq.Unmarshal(m, b)
}
func (m *ModuleDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleDeleteReq.Marshal(b, m, deterministic)
}
func (m *ModuleDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleDeleteReq.Merge(m, src)
}
func (m *ModuleDeleteReq) XXX_Size() int {
	return xxx_messageInfo_ModuleDeleteReq.Size(m)
}
func (m *ModuleDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleDeleteReq proto.InternalMessageInfo

func (m *ModuleDeleteReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ModuleInfoReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleInfoReq) Reset()         { *m = ModuleInfoReq{} }
func (m *ModuleInfoReq) String() string { return proto.CompactTextString(m) }
func (*ModuleInfoReq) ProtoMessage()    {}
func (*ModuleInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{7}
}

func (m *ModuleInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleInfoReq.Unmarshal(m, b)
}
func (m *ModuleInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleInfoReq.Marshal(b, m, deterministic)
}
func (m *ModuleInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleInfoReq.Merge(m, src)
}
func (m *ModuleInfoReq) XXX_Size() int {
	return xxx_messageInfo_ModuleInfoReq.Size(m)
}
func (m *ModuleInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleInfoReq proto.InternalMessageInfo

func (m *ModuleInfoReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ModuleInfoRes struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ModuleInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ModuleInfoRes) Reset()         { *m = ModuleInfoRes{} }
func (m *ModuleInfoRes) String() string { return proto.CompactTextString(m) }
func (*ModuleInfoRes) ProtoMessage()    {}
func (*ModuleInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f858cd7690f3b7, []int{8}
}

func (m *ModuleInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleInfoRes.Unmarshal(m, b)
}
func (m *ModuleInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleInfoRes.Marshal(b, m, deterministic)
}
func (m *ModuleInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleInfoRes.Merge(m, src)
}
func (m *ModuleInfoRes) XXX_Size() int {
	return xxx_messageInfo_ModuleInfoRes.Size(m)
}
func (m *ModuleInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleInfoRes proto.InternalMessageInfo

func (m *ModuleInfoRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModuleInfoRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ModuleInfoRes) GetData() *ModuleInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ModuleInfo)(nil), "app.ModuleInfo")
	proto.RegisterType((*ModuleCreateReq)(nil), "app.ModuleCreateReq")
	proto.RegisterType((*ModuleUpdateReq)(nil), "app.ModuleUpdateReq")
	proto.RegisterType((*ModuleListReq)(nil), "app.ModuleListReq")
	proto.RegisterType((*ModuleListData)(nil), "app.ModuleListData")
	proto.RegisterType((*ModuleListRes)(nil), "app.ModuleListRes")
	proto.RegisterType((*ModuleDeleteReq)(nil), "app.ModuleDeleteReq")
	proto.RegisterType((*ModuleInfoReq)(nil), "app.ModuleInfoReq")
	proto.RegisterType((*ModuleInfoRes)(nil), "app.ModuleInfoRes")
}

func init() { proto.RegisterFile("app/module.proto", fileDescriptor_44f858cd7690f3b7) }

var fileDescriptor_44f858cd7690f3b7 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x8e, 0x9d, 0x36, 0x13, 0x9a, 0x94, 0xa5, 0x12, 0x2b, 0x03, 0x22, 0xb8, 0x48, 0x84,
	0x4b, 0x2c, 0x15, 0x89, 0x0b, 0x27, 0x42, 0x2e, 0x11, 0x1f, 0x87, 0x45, 0x5c, 0x7a, 0x40, 0xda,
	0xda, 0xdb, 0xca, 0x92, 0x63, 0x2f, 0xf1, 0x06, 0x09, 0xfe, 0x2a, 0xff, 0xa4, 0x07, 0x84, 0x66,
	0xd6, 0xeb, 0xd4, 0x49, 0x84, 0xf0, 0x69, 0xe6, 0xcd, 0xc7, 0x3e, 0xbd, 0x37, 0x32, 0x9c, 0x4a,
	0xad, 0x93, 0x55, 0x95, 0x6d, 0x0a, 0x35, 0xd3, 0xeb, 0xca, 0x54, 0xac, 0x27, 0xb5, 0x8e, 0x46,
	0x08, 0x5f, 0xc9, 0xba, 0x01, 0xa3, 0x47, 0x3f, 0x64, 0x91, 0x67, 0xd2, 0xa8, 0xc4, 0x05, 0xb6,
	0x10, 0xff, 0xf6, 0x01, 0x3e, 0xd1, 0xf8, 0xb2, 0xbc, 0xae, 0xd8, 0x53, 0x08, 0xa5, 0xd6, 0xcb,
	0x05, 0xf7, 0x26, 0xde, 0x34, 0x9c, 0x1f, 0xdd, 0xce, 0x83, 0xc8, 0x9f, 0x7a, 0xc2, 0xa2, 0x6c,
	0x04, 0xfe, 0x72, 0xc1, 0x7d, 0xac, 0x09, 0x7f, 0xb9, 0x60, 0x8f, 0x21, 0x28, 0xe5, 0x4a, 0xf1,
	0xde, 0xc4, 0x9b, 0x0e, 0xa8, 0x7b, 0xed, 0x4f, 0x3c, 0x41, 0x20, 0x63, 0x10, 0xa4, 0x55, 0xa6,
	0x78, 0x80, 0x45, 0x41, 0x31, 0x0e, 0xe4, 0x69, 0x55, 0xf2, 0x70, 0x67, 0x00, 0x41, 0xf6, 0x02,
	0x42, 0xbd, 0xce, 0x53, 0xc5, 0xfb, 0x13, 0x6f, 0xea, 0xcd, 0x47, 0xb7, 0xf3, 0x21, 0x1b, 0xbc,
	0xba, 0xd7, 0x7c, 0xc2, 0x16, 0x71, 0xed, 0xa6, 0xcc, 0x0d, 0x3f, 0x22, 0x16, 0x14, 0x23, 0x66,
	0x7e, 0x6a, 0xc5, 0x8f, 0x2d, 0x86, 0x31, 0x62, 0x99, 0xaa, 0x53, 0x3e, 0xb0, 0xcf, 0x63, 0xcc,
	0x38, 0x1c, 0xa5, 0x55, 0x69, 0x54, 0x69, 0x38, 0x10, 0xec, 0x52, 0xf6, 0x04, 0x06, 0xe9, 0x5a,
	0x49, 0xa3, 0xb2, 0x77, 0x86, 0x0f, 0xa9, 0xb6, 0x05, 0xb0, 0xba, 0xd1, 0x59, 0x53, 0xbd, 0x6f,
	0xab, 0x2d, 0x80, 0x5b, 0xa5, 0xd6, 0x9f, 0x51, 0x88, 0x13, 0xbb, 0xb5, 0x49, 0xe3, 0x37, 0x30,
	0xb6, 0xe2, 0xbe, 0xa7, 0x55, 0x42, 0x7d, 0x67, 0xe7, 0x10, 0x64, 0xd2, 0x48, 0x12, 0x78, 0x78,
	0x31, 0x9e, 0x49, 0xad, 0x67, 0x5b, 0x03, 0x04, 0x15, 0x63, 0xe1, 0xe6, 0xbe, 0xd2, 0x23, 0x38,
	0x17, 0xc1, 0xb1, 0xb5, 0xd9, 0x99, 0x23, 0xda, 0xbc, 0xdd, 0xe9, 0xff, 0x6b, 0x67, 0x0e, 0x27,
	0x16, 0xfb, 0x98, 0xd7, 0x06, 0x37, 0x9e, 0x75, 0xbc, 0x76, 0x16, 0xb3, 0xc6, 0x52, 0xdf, 0xca,
	0x46, 0x4e, 0x46, 0x70, 0xac, 0xe5, 0x8d, 0xfa, 0x92, 0xff, 0xb2, 0x56, 0x87, 0xa2, 0xcd, 0xb1,
	0x1f, 0x63, 0x72, 0x39, 0x14, 0x14, 0xc7, 0x1f, 0x60, 0xb4, 0x7d, 0x6a, 0x21, 0x8d, 0xc4, 0xb7,
	0x4c, 0x65, 0x64, 0xe1, 0xde, 0xa2, 0x04, 0x79, 0x17, 0x79, 0x6d, 0xb8, 0x3f, 0xe9, 0x1d, 0xe4,
	0x8d, 0xc5, 0xf8, 0x5b, 0x97, 0x77, 0xdd, 0xde, 0x95, 0x5d, 0x65, 0xef, 0xea, 0x14, 0x7a, 0xab,
	0xfa, 0xa6, 0x21, 0x8d, 0x21, 0x7b, 0xd9, 0x68, 0xd2, 0x23, 0x4d, 0x1e, 0xde, 0xd9, 0xed, 0x48,
	0x35, 0xba, 0x3c, 0x77, 0x5a, 0x2f, 0x54, 0xa1, 0xac, 0xd6, 0xf6, 0xcc, 0x3d, 0x77, 0xe6, 0xf1,
	0x33, 0x47, 0x81, 0x68, 0x1d, 0x68, 0xb8, 0xec, 0x36, 0xfc, 0x2f, 0xc7, 0xf3, 0x0e, 0xc7, 0xc3,
	0xbe, 0x5d, 0xfc, 0xf1, 0x60, 0x20, 0xb5, 0xb6, 0x38, 0x4b, 0xa0, 0x6f, 0x6f, 0x89, 0x9d, 0xdd,
	0x69, 0x6f, 0xcf, 0x2b, 0xb2, 0x4b, 0x32, 0x75, 0x2d, 0x37, 0x05, 0xa9, 0x95, 0x40, 0xdf, 0x1e,
	0x51, 0x67, 0xa0, 0xbd, 0xab, 0xfd, 0x81, 0x19, 0x04, 0xa8, 0x10, 0x63, 0x3b, 0x92, 0x61, 0xf3,
	0x3e, 0x46, 0xfd, 0xf4, 0xeb, 0x60, 0xbb, 0xf4, 0x77, 0xfa, 0x9d, 0x34, 0x09, 0xf4, 0xad, 0xd2,
	0x1d, 0x42, 0xad, 0xf8, 0x7b, 0x84, 0xe6, 0x0f, 0x2e, 0xc7, 0xb3, 0x84, 0xfe, 0x56, 0x89, 0xd4,
	0xfa, 0xad, 0xd4, 0xfa, 0xaa, 0x4f, 0xe9, 0xeb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x5b,
	0xab, 0xc9, 0xfe, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppModuleClient is the client API for AppModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppModuleClient interface {
	Create(ctx context.Context, in *ModuleCreateReq, opts ...grpc.CallOption) (*DefaultRes, error)
	Update(ctx context.Context, in *ModuleUpdateReq, opts ...grpc.CallOption) (*DefaultRes, error)
	List(ctx context.Context, in *ModuleListReq, opts ...grpc.CallOption) (*ModuleListRes, error)
	Info(ctx context.Context, in *ModuleInfoReq, opts ...grpc.CallOption) (*ModuleInfoRes, error)
	Delete(ctx context.Context, in *ModuleDeleteReq, opts ...grpc.CallOption) (*DefaultRes, error)
}

type appModuleClient struct {
	cc *grpc.ClientConn
}

func NewAppModuleClient(cc *grpc.ClientConn) AppModuleClient {
	return &appModuleClient{cc}
}

func (c *appModuleClient) Create(ctx context.Context, in *ModuleCreateReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/app.appModule/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appModuleClient) Update(ctx context.Context, in *ModuleUpdateReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/app.appModule/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appModuleClient) List(ctx context.Context, in *ModuleListReq, opts ...grpc.CallOption) (*ModuleListRes, error) {
	out := new(ModuleListRes)
	err := c.cc.Invoke(ctx, "/app.appModule/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appModuleClient) Info(ctx context.Context, in *ModuleInfoReq, opts ...grpc.CallOption) (*ModuleInfoRes, error) {
	out := new(ModuleInfoRes)
	err := c.cc.Invoke(ctx, "/app.appModule/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appModuleClient) Delete(ctx context.Context, in *ModuleDeleteReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/app.appModule/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppModuleServer is the server API for AppModule service.
type AppModuleServer interface {
	Create(context.Context, *ModuleCreateReq) (*DefaultRes, error)
	Update(context.Context, *ModuleUpdateReq) (*DefaultRes, error)
	List(context.Context, *ModuleListReq) (*ModuleListRes, error)
	Info(context.Context, *ModuleInfoReq) (*ModuleInfoRes, error)
	Delete(context.Context, *ModuleDeleteReq) (*DefaultRes, error)
}

// UnimplementedAppModuleServer can be embedded to have forward compatible implementations.
type UnimplementedAppModuleServer struct {
}

func (*UnimplementedAppModuleServer) Create(ctx context.Context, req *ModuleCreateReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAppModuleServer) Update(ctx context.Context, req *ModuleUpdateReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAppModuleServer) List(ctx context.Context, req *ModuleListReq) (*ModuleListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAppModuleServer) Info(ctx context.Context, req *ModuleInfoReq) (*ModuleInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedAppModuleServer) Delete(ctx context.Context, req *ModuleDeleteReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterAppModuleServer(s *grpc.Server, srv AppModuleServer) {
	s.RegisterService(&_AppModule_serviceDesc, srv)
}

func _AppModule_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppModuleServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.appModule/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppModuleServer).Create(ctx, req.(*ModuleCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppModule_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppModuleServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.appModule/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppModuleServer).Update(ctx, req.(*ModuleUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppModule_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppModuleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.appModule/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppModuleServer).List(ctx, req.(*ModuleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppModule_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppModuleServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.appModule/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppModuleServer).Info(ctx, req.(*ModuleInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppModule_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppModuleServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.appModule/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppModuleServer).Delete(ctx, req.(*ModuleDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppModule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.appModule",
	HandlerType: (*AppModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AppModule_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AppModule_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AppModule_List_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _AppModule_Info_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AppModule_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/module.proto",
}
