// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rbac/base.proto

package rbac

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DefaultRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultRes) Reset()         { *m = DefaultRes{} }
func (m *DefaultRes) String() string { return proto.CompactTextString(m) }
func (*DefaultRes) ProtoMessage()    {}
func (*DefaultRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a20ea06e40391a, []int{0}
}

func (m *DefaultRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultRes.Unmarshal(m, b)
}
func (m *DefaultRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultRes.Marshal(b, m, deterministic)
}
func (m *DefaultRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultRes.Merge(m, src)
}
func (m *DefaultRes) XXX_Size() int {
	return xxx_messageInfo_DefaultRes.Size(m)
}
func (m *DefaultRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultRes.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultRes proto.InternalMessageInfo

func (m *DefaultRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DefaultRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DefaultRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a20ea06e40391a, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DefaultRes)(nil), "rbac.defaultRes")
	proto.RegisterType((*Empty)(nil), "rbac.empty")
}

func init() { proto.RegisterFile("rbac/base.proto", fileDescriptor_73a20ea06e40391a) }

var fileDescriptor_73a20ea06e40391a = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x4a, 0x4c,
	0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x09, 0x28,
	0xb9, 0x71, 0x71, 0xa5, 0xa4, 0xa6, 0x25, 0x96, 0xe6, 0x94, 0x04, 0xa5, 0x16, 0x0b, 0x09, 0x71,
	0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x02,
	0x5c, 0xcc, 0xb9, 0xc5, 0xe9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0x26, 0x48, 0x55,
	0x4a, 0x62, 0x49, 0xa2, 0x04, 0x33, 0x58, 0x08, 0xcc, 0x56, 0x62, 0xe7, 0x62, 0x4d, 0xcd, 0x2d,
	0x28, 0xa9, 0x74, 0x12, 0x8e, 0x12, 0xd4, 0xd3, 0x07, 0xdb, 0xa0, 0x0f, 0xb2, 0xc0, 0x1a, 0x44,
	0x24, 0xb1, 0x81, 0x05, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x24, 0x02, 0x90, 0x85,
	0x00, 0x00, 0x00,
}
