// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rbac/role.proto

package rbac

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleInfo struct {
	//@inject_tag: json:"id"
	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	//@inject_tag: json:"name" binding:"required"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" binding:"required"`
	//@inject_tag: json:"is_root"
	IsRoot int32 `protobuf:"varint,3,opt,name=isRoot,proto3" json:"is_root"`
	//@inject_tag: json:"status"
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{0}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RoleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleInfo) GetIsRoot() int32 {
	if m != nil {
		return m.IsRoot
	}
	return 0
}

func (m *RoleInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type SetPermissionReq struct {
	//@inject_tag: json:"role_id" binding:"required"
	RoleID int32 `protobuf:"varint,1,opt,name=roleID,proto3" json:"role_id" binding:"required"`
	//@inject_tag: json:"permission_ids" binding:"required"
	PermissionIDs        []int32  `protobuf:"varint,2,rep,packed,name=permissionIDs,proto3" json:"permission_ids" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPermissionReq) Reset()         { *m = SetPermissionReq{} }
func (m *SetPermissionReq) String() string { return proto.CompactTextString(m) }
func (*SetPermissionReq) ProtoMessage()    {}
func (*SetPermissionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{1}
}

func (m *SetPermissionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPermissionReq.Unmarshal(m, b)
}
func (m *SetPermissionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPermissionReq.Marshal(b, m, deterministic)
}
func (m *SetPermissionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPermissionReq.Merge(m, src)
}
func (m *SetPermissionReq) XXX_Size() int {
	return xxx_messageInfo_SetPermissionReq.Size(m)
}
func (m *SetPermissionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPermissionReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetPermissionReq proto.InternalMessageInfo

func (m *SetPermissionReq) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *SetPermissionReq) GetPermissionIDs() []int32 {
	if m != nil {
		return m.PermissionIDs
	}
	return nil
}

type PermissionListReq struct {
	//@inject_tag: json:"role_id" binding:"required"
	RoleID               int32    `protobuf:"varint,1,opt,name=roleID,proto3" json:"role_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionListReq) Reset()         { *m = PermissionListReq{} }
func (m *PermissionListReq) String() string { return proto.CompactTextString(m) }
func (*PermissionListReq) ProtoMessage()    {}
func (*PermissionListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{2}
}

func (m *PermissionListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionListReq.Unmarshal(m, b)
}
func (m *PermissionListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionListReq.Marshal(b, m, deterministic)
}
func (m *PermissionListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionListReq.Merge(m, src)
}
func (m *PermissionListReq) XXX_Size() int {
	return xxx_messageInfo_PermissionListReq.Size(m)
}
func (m *PermissionListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionListReq proto.InternalMessageInfo

func (m *PermissionListReq) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type PermissionData struct {
	//@inject_tag: json:"permission_ids"
	PermissionIDs        []int32  `protobuf:"varint,3,rep,packed,name=permissionIDs,proto3" json:"permission_ids"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionData) Reset()         { *m = PermissionData{} }
func (m *PermissionData) String() string { return proto.CompactTextString(m) }
func (*PermissionData) ProtoMessage()    {}
func (*PermissionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{3}
}

func (m *PermissionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionData.Unmarshal(m, b)
}
func (m *PermissionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionData.Marshal(b, m, deterministic)
}
func (m *PermissionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionData.Merge(m, src)
}
func (m *PermissionData) XXX_Size() int {
	return xxx_messageInfo_PermissionData.Size(m)
}
func (m *PermissionData) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionData.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionData proto.InternalMessageInfo

func (m *PermissionData) GetPermissionIDs() []int32 {
	if m != nil {
		return m.PermissionIDs
	}
	return nil
}

type PermissionRes struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *PermissionData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PermissionRes) Reset()         { *m = PermissionRes{} }
func (m *PermissionRes) String() string { return proto.CompactTextString(m) }
func (*PermissionRes) ProtoMessage()    {}
func (*PermissionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{4}
}

func (m *PermissionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionRes.Unmarshal(m, b)
}
func (m *PermissionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionRes.Marshal(b, m, deterministic)
}
func (m *PermissionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionRes.Merge(m, src)
}
func (m *PermissionRes) XXX_Size() int {
	return xxx_messageInfo_PermissionRes.Size(m)
}
func (m *PermissionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionRes.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionRes proto.InternalMessageInfo

func (m *PermissionRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PermissionRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PermissionRes) GetData() *PermissionData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RoleCreateReq struct {
	Data *RoleInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	//@inject_tag: json:"permission_ids" binding:"required"
	PermissionIDs        []int32  `protobuf:"varint,5,rep,packed,name=permissionIDs,proto3" json:"permission_ids" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleCreateReq) Reset()         { *m = RoleCreateReq{} }
func (m *RoleCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoleCreateReq) ProtoMessage()    {}
func (*RoleCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{5}
}

func (m *RoleCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleCreateReq.Unmarshal(m, b)
}
func (m *RoleCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleCreateReq.Marshal(b, m, deterministic)
}
func (m *RoleCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleCreateReq.Merge(m, src)
}
func (m *RoleCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoleCreateReq.Size(m)
}
func (m *RoleCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleCreateReq proto.InternalMessageInfo

func (m *RoleCreateReq) GetData() *RoleInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoleCreateReq) GetPermissionIDs() []int32 {
	if m != nil {
		return m.PermissionIDs
	}
	return nil
}

type RoleUpdateReq struct {
	RoleID int32     `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	Data   *RoleInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	//@inject_tag: json:"permission_ids" binding:"required"
	PermissionIDs        []int32  `protobuf:"varint,5,rep,packed,name=permissionIDs,proto3" json:"permission_ids" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleUpdateReq) Reset()         { *m = RoleUpdateReq{} }
func (m *RoleUpdateReq) String() string { return proto.CompactTextString(m) }
func (*RoleUpdateReq) ProtoMessage()    {}
func (*RoleUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{6}
}

func (m *RoleUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleUpdateReq.Unmarshal(m, b)
}
func (m *RoleUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleUpdateReq.Marshal(b, m, deterministic)
}
func (m *RoleUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleUpdateReq.Merge(m, src)
}
func (m *RoleUpdateReq) XXX_Size() int {
	return xxx_messageInfo_RoleUpdateReq.Size(m)
}
func (m *RoleUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleUpdateReq proto.InternalMessageInfo

func (m *RoleUpdateReq) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *RoleUpdateReq) GetData() *RoleInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoleUpdateReq) GetPermissionIDs() []int32 {
	if m != nil {
		return m.PermissionIDs
	}
	return nil
}

type RoleDeleteReq struct {
	RoleID               int32    `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleDeleteReq) Reset()         { *m = RoleDeleteReq{} }
func (m *RoleDeleteReq) String() string { return proto.CompactTextString(m) }
func (*RoleDeleteReq) ProtoMessage()    {}
func (*RoleDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{7}
}

func (m *RoleDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDeleteReq.Unmarshal(m, b)
}
func (m *RoleDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDeleteReq.Marshal(b, m, deterministic)
}
func (m *RoleDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDeleteReq.Merge(m, src)
}
func (m *RoleDeleteReq) XXX_Size() int {
	return xxx_messageInfo_RoleDeleteReq.Size(m)
}
func (m *RoleDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDeleteReq proto.InternalMessageInfo

func (m *RoleDeleteReq) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type RoleListReq struct {
	//@inject_tag: form:"company_id"
	CompanyID int32 `protobuf:"varint,1,opt,name=companyID,proto3" json:"companyID,omitempty" form:"company_id"`
	//@inject_tag: form:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name"`
	//@inject_tag: form:"page"
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" form:"page"`
	//@inject_tag: form:"page_size"
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty" form:"page_size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleListReq) Reset()         { *m = RoleListReq{} }
func (m *RoleListReq) String() string { return proto.CompactTextString(m) }
func (*RoleListReq) ProtoMessage()    {}
func (*RoleListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{8}
}

func (m *RoleListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListReq.Unmarshal(m, b)
}
func (m *RoleListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListReq.Marshal(b, m, deterministic)
}
func (m *RoleListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListReq.Merge(m, src)
}
func (m *RoleListReq) XXX_Size() int {
	return xxx_messageInfo_RoleListReq.Size(m)
}
func (m *RoleListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListReq proto.InternalMessageInfo

func (m *RoleListReq) GetCompanyID() int32 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *RoleListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RoleListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type RoleListData struct {
	//@inject_tag: json:"list"
	List []*RoleInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	//@inject_tag: json:"total"
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleListData) Reset()         { *m = RoleListData{} }
func (m *RoleListData) String() string { return proto.CompactTextString(m) }
func (*RoleListData) ProtoMessage()    {}
func (*RoleListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{9}
}

func (m *RoleListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListData.Unmarshal(m, b)
}
func (m *RoleListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListData.Marshal(b, m, deterministic)
}
func (m *RoleListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListData.Merge(m, src)
}
func (m *RoleListData) XXX_Size() int {
	return xxx_messageInfo_RoleListData.Size(m)
}
func (m *RoleListData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListData.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListData proto.InternalMessageInfo

func (m *RoleListData) GetList() []*RoleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *RoleListData) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type RoleListRes struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *RoleListData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoleListRes) Reset()         { *m = RoleListRes{} }
func (m *RoleListRes) String() string { return proto.CompactTextString(m) }
func (*RoleListRes) ProtoMessage()    {}
func (*RoleListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a75e6c72f6e386, []int{10}
}

func (m *RoleListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListRes.Unmarshal(m, b)
}
func (m *RoleListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListRes.Marshal(b, m, deterministic)
}
func (m *RoleListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListRes.Merge(m, src)
}
func (m *RoleListRes) XXX_Size() int {
	return xxx_messageInfo_RoleListRes.Size(m)
}
func (m *RoleListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListRes proto.InternalMessageInfo

func (m *RoleListRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RoleListRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RoleListRes) GetData() *RoleListData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RoleInfo)(nil), "rbac.roleInfo")
	proto.RegisterType((*SetPermissionReq)(nil), "rbac.setPermissionReq")
	proto.RegisterType((*PermissionListReq)(nil), "rbac.permissionListReq")
	proto.RegisterType((*PermissionData)(nil), "rbac.permissionData")
	proto.RegisterType((*PermissionRes)(nil), "rbac.permissionRes")
	proto.RegisterType((*RoleCreateReq)(nil), "rbac.roleCreateReq")
	proto.RegisterType((*RoleUpdateReq)(nil), "rbac.roleUpdateReq")
	proto.RegisterType((*RoleDeleteReq)(nil), "rbac.roleDeleteReq")
	proto.RegisterType((*RoleListReq)(nil), "rbac.roleListReq")
	proto.RegisterType((*RoleListData)(nil), "rbac.roleListData")
	proto.RegisterType((*RoleListRes)(nil), "rbac.roleListRes")
}

func init() { proto.RegisterFile("rbac/role.proto", fileDescriptor_23a75e6c72f6e386) }

var fileDescriptor_23a75e6c72f6e386 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5f, 0x8b, 0xd3, 0x4e,
	0x14, 0x25, 0xc9, 0xb4, 0xbf, 0xdd, 0xbb, 0xbf, 0xad, 0xed, 0x74, 0xd9, 0x0d, 0x51, 0xb0, 0x0c,
	0x22, 0x01, 0xa5, 0x91, 0x15, 0x7c, 0x11, 0x7c, 0xa8, 0x79, 0xb0, 0xe0, 0xc3, 0x32, 0xe2, 0xc3,
	0xea, 0x83, 0x4c, 0x9b, 0xd9, 0x12, 0x48, 0x3b, 0x31, 0x33, 0x2b, 0xb8, 0x5f, 0xc0, 0xef, 0xec,
	0x93, 0xcc, 0x9f, 0x24, 0xcd, 0x36, 0xe0, 0x82, 0x2f, 0xed, 0xcc, 0x99, 0x7b, 0xee, 0x39, 0x99,
	0x7b, 0x12, 0x78, 0x54, 0xad, 0xd8, 0x3a, 0xa9, 0x44, 0xc1, 0xe7, 0x65, 0x25, 0x94, 0xc0, 0x48,
	0x03, 0x91, 0x85, 0x57, 0x4c, 0x3a, 0x38, 0xba, 0xf8, 0xc1, 0x8a, 0x3c, 0x63, 0x8a, 0x27, 0xf5,
	0xc2, 0x1e, 0x90, 0x0d, 0x1c, 0x69, 0xf6, 0x72, 0x77, 0x23, 0xf0, 0x08, 0xfc, 0x65, 0x1a, 0x7a,
	0x33, 0x2f, 0x1e, 0x50, 0x7f, 0x99, 0xe2, 0xc7, 0x80, 0x76, 0x6c, 0xcb, 0x43, 0x7f, 0xe6, 0xc5,
	0xc7, 0x8b, 0xff, 0x7e, 0x2f, 0x50, 0xe5, 0x8f, 0x3d, 0x6a, 0x40, 0x7c, 0x0e, 0xc3, 0x5c, 0x52,
	0x21, 0x54, 0x18, 0x18, 0x82, 0xdb, 0x69, 0x5c, 0x2a, 0xa6, 0x6e, 0x65, 0x88, 0x2c, 0x6e, 0x77,
	0xe4, 0x1a, 0xc6, 0x92, 0xab, 0x2b, 0x5e, 0x6d, 0x73, 0x29, 0x73, 0xb1, 0xa3, 0xfc, 0x3b, 0x7e,
	0x0a, 0x43, 0x23, 0xee, 0x44, 0x8d, 0x44, 0xe4, 0xc7, 0x1e, 0x75, 0x30, 0x7e, 0x06, 0xa7, 0x65,
	0xc3, 0x58, 0xa6, 0x32, 0xf4, 0x67, 0x41, 0x3c, 0xa0, 0x5d, 0x90, 0xbc, 0x80, 0x49, 0x0b, 0x7c,
	0xcc, 0xa5, 0xd2, 0xbd, 0xcf, 0xbb, 0xbd, 0xeb, 0x96, 0xe4, 0x0d, 0x8c, 0xda, 0xe2, 0x94, 0x29,
	0x76, 0x28, 0x12, 0xf4, 0x89, 0x7c, 0xdb, 0xaf, 0xa2, 0x5c, 0x62, 0x0c, 0x68, 0x2d, 0x32, 0xee,
	0xda, 0x9b, 0x35, 0x1e, 0x43, 0xb0, 0x95, 0x1b, 0x7b, 0x61, 0x54, 0x2f, 0x71, 0x0c, 0x28, 0x63,
	0x8a, 0x99, 0x4b, 0x3a, 0xb9, 0x3c, 0x9b, 0xeb, 0xc1, 0xcc, 0xbb, 0x06, 0xa8, 0xa9, 0x20, 0xd7,
	0x70, 0xaa, 0x2d, 0xbe, 0xaf, 0x38, 0x53, 0x5c, 0x3f, 0x01, 0x71, 0x54, 0xcf, 0x50, 0x47, 0x96,
	0x5a, 0x0f, 0xcb, 0x92, 0x0e, 0xbd, 0x0f, 0xfa, 0xbc, 0xdf, 0xd9, 0xd6, 0x9f, 0xcb, 0xcc, 0xb5,
	0xfe, 0xeb, 0xc5, 0xd7, 0xda, 0xfe, 0x3f, 0x6b, 0xbf, 0xb2, 0xda, 0x29, 0x2f, 0xf8, 0xc3, 0xb4,
	0x89, 0x80, 0x13, 0xbd, 0xaa, 0x07, 0xf9, 0x04, 0x8e, 0xd7, 0x62, 0x5b, 0xb2, 0xdd, 0xcf, 0x66,
	0x96, 0x2d, 0xa0, 0xa7, 0xd0, 0x66, 0xd4, 0x45, 0x13, 0x03, 0x2a, 0xd9, 0x86, 0xbb, 0x60, 0x9a,
	0x35, 0x8e, 0xe0, 0x48, 0xff, 0x7f, 0xca, 0xef, 0xb8, 0x0b, 0x66, 0xb3, 0x27, 0x1f, 0xe0, 0xff,
	0x5a, 0xd0, 0x04, 0x82, 0x00, 0x2a, 0x72, 0xa9, 0x42, 0x6f, 0x16, 0xf4, 0x3d, 0xbc, 0x3e, 0xc3,
	0x67, 0x30, 0x50, 0x42, 0xb1, 0xc2, 0x08, 0x07, 0xd4, 0x6e, 0xc8, 0xd7, 0x7d, 0xeb, 0x0f, 0x8d,
	0xc8, 0xf3, 0x4e, 0x44, 0x70, 0x2b, 0x57, 0x1b, 0xb2, 0xf7, 0x7d, 0xf9, 0xcb, 0x07, 0xa4, 0x61,
	0x9c, 0xc0, 0xd0, 0xa6, 0x04, 0x4f, 0xdb, 0xe2, 0x26, 0x37, 0xd1, 0xd8, 0x82, 0x19, 0xbf, 0x61,
	0xb7, 0x85, 0xf1, 0x91, 0xc0, 0xd0, 0xce, 0x7e, 0x9f, 0xd0, 0xa4, 0xa1, 0x9f, 0x60, 0x07, 0xb6,
	0x4f, 0x68, 0x46, 0xd8, 0x43, 0x78, 0x09, 0x48, 0xbb, 0xc5, 0x93, 0xae, 0x7b, 0x5d, 0x7c, 0x00,
	0x49, 0xfc, 0x0e, 0x46, 0x57, 0x9d, 0x17, 0x16, 0x5f, 0xdc, 0x7f, 0x31, 0x6a, 0xf6, 0xf4, 0xfe,
	0x01, 0xe5, 0x72, 0x31, 0xfd, 0x32, 0x99, 0x27, 0xe6, 0xfb, 0x95, 0xe8, 0xd3, 0xb7, 0xfa, 0x67,
	0x35, 0x34, 0xc0, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x3c, 0xf2, 0x57, 0x13, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoleClient is the client API for Role service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoleClient interface {
	//  管理
	Create(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*DefaultRes, error)
	Update(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*DefaultRes, error)
	Delete(ctx context.Context, in *RoleDeleteReq, opts ...grpc.CallOption) (*DefaultRes, error)
	List(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListRes, error)
	//  rpc SetPermission(setPermissionReq)returns(defaultRes);
	PermissionList(ctx context.Context, in *PermissionListReq, opts ...grpc.CallOption) (*PermissionRes, error)
}

type roleClient struct {
	cc *grpc.ClientConn
}

func NewRoleClient(cc *grpc.ClientConn) RoleClient {
	return &roleClient{cc}
}

func (c *roleClient) Create(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.role/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) Update(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.role/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) Delete(ctx context.Context, in *RoleDeleteReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.role/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) List(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListRes, error) {
	out := new(RoleListRes)
	err := c.cc.Invoke(ctx, "/rbac.role/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) PermissionList(ctx context.Context, in *PermissionListReq, opts ...grpc.CallOption) (*PermissionRes, error) {
	out := new(PermissionRes)
	err := c.cc.Invoke(ctx, "/rbac.role/PermissionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServer is the server API for Role service.
type RoleServer interface {
	//  管理
	Create(context.Context, *RoleCreateReq) (*DefaultRes, error)
	Update(context.Context, *RoleUpdateReq) (*DefaultRes, error)
	Delete(context.Context, *RoleDeleteReq) (*DefaultRes, error)
	List(context.Context, *RoleListReq) (*RoleListRes, error)
	//  rpc SetPermission(setPermissionReq)returns(defaultRes);
	PermissionList(context.Context, *PermissionListReq) (*PermissionRes, error)
}

// UnimplementedRoleServer can be embedded to have forward compatible implementations.
type UnimplementedRoleServer struct {
}

func (*UnimplementedRoleServer) Create(ctx context.Context, req *RoleCreateReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedRoleServer) Update(ctx context.Context, req *RoleUpdateReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedRoleServer) Delete(ctx context.Context, req *RoleDeleteReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedRoleServer) List(ctx context.Context, req *RoleListReq) (*RoleListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedRoleServer) PermissionList(ctx context.Context, req *PermissionListReq) (*PermissionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PermissionList not implemented")
}

func RegisterRoleServer(s *grpc.Server, srv RoleServer) {
	s.RegisterService(&_Role_serviceDesc, srv)
}

func _Role_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.role/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).Create(ctx, req.(*RoleCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.role/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).Update(ctx, req.(*RoleUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.role/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).Delete(ctx, req.(*RoleDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.role/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).List(ctx, req.(*RoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_PermissionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).PermissionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.role/PermissionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).PermissionList(ctx, req.(*PermissionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Role_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rbac.role",
	HandlerType: (*RoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Role_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Role_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Role_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Role_List_Handler,
		},
		{
			MethodName: "PermissionList",
			Handler:    _Role_PermissionList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rbac/role.proto",
}
