// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rbac/user.proto

package rbac

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	//@inject_tag: json:"id"
	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	//@inject_tag: json:"company_id" binding:"required"
	CompanyID int32 `protobuf:"varint,2,opt,name=companyID,proto3" json:"company_id" binding:"required"`
	//@inject_tag: json:"account_id" binding:"required"
	AccountID int32 `protobuf:"varint,3,opt,name=accountID,proto3" json:"account_id" binding:"required"`
	//@inject_tag: json:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	//@inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar"`
	//@inject_tag: json:"activity_status"
	ActivityStatus int32 `protobuf:"varint,6,opt,name=activityStatus,proto3" json:"activity_status"`
	//@inject_tag: json:"status"
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserInfo) GetCompanyID() int32 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *UserInfo) GetAccountID() int32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetActivityStatus() int32 {
	if m != nil {
		return m.ActivityStatus
	}
	return 0
}

func (m *UserInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UserRolesReq struct {
	//@inject_tag: form:"uid" binding:"required"
	UID                  int32    `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty" form:"uid" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRolesReq) Reset()         { *m = UserRolesReq{} }
func (m *UserRolesReq) String() string { return proto.CompactTextString(m) }
func (*UserRolesReq) ProtoMessage()    {}
func (*UserRolesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{1}
}

func (m *UserRolesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRolesReq.Unmarshal(m, b)
}
func (m *UserRolesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRolesReq.Marshal(b, m, deterministic)
}
func (m *UserRolesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRolesReq.Merge(m, src)
}
func (m *UserRolesReq) XXX_Size() int {
	return xxx_messageInfo_UserRolesReq.Size(m)
}
func (m *UserRolesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRolesReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserRolesReq proto.InternalMessageInfo

func (m *UserRolesReq) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

type UserRolesData struct {
	//@inject_tag: json:"role_ids"
	RoleIDs              []int32  `protobuf:"varint,1,rep,packed,name=roleIDs,proto3" json:"role_ids"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRolesData) Reset()         { *m = UserRolesData{} }
func (m *UserRolesData) String() string { return proto.CompactTextString(m) }
func (*UserRolesData) ProtoMessage()    {}
func (*UserRolesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{2}
}

func (m *UserRolesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRolesData.Unmarshal(m, b)
}
func (m *UserRolesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRolesData.Marshal(b, m, deterministic)
}
func (m *UserRolesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRolesData.Merge(m, src)
}
func (m *UserRolesData) XXX_Size() int {
	return xxx_messageInfo_UserRolesData.Size(m)
}
func (m *UserRolesData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRolesData.DiscardUnknown(m)
}

var xxx_messageInfo_UserRolesData proto.InternalMessageInfo

func (m *UserRolesData) GetRoleIDs() []int32 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

type UserRolesRes struct {
	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	//@inject_tag: json:"data"
	Data                 *UserRolesData `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserRolesRes) Reset()         { *m = UserRolesRes{} }
func (m *UserRolesRes) String() string { return proto.CompactTextString(m) }
func (*UserRolesRes) ProtoMessage()    {}
func (*UserRolesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{3}
}

func (m *UserRolesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRolesRes.Unmarshal(m, b)
}
func (m *UserRolesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRolesRes.Marshal(b, m, deterministic)
}
func (m *UserRolesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRolesRes.Merge(m, src)
}
func (m *UserRolesRes) XXX_Size() int {
	return xxx_messageInfo_UserRolesRes.Size(m)
}
func (m *UserRolesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRolesRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserRolesRes proto.InternalMessageInfo

func (m *UserRolesRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserRolesRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserRolesRes) GetData() *UserRolesData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetUserStatusReq struct {
	//@inject_tag: json:"uid"
	UID int32 `protobuf:"varint,1,opt,name=uID,proto3" json:"uid"`
	//@inject_tag: json:"status" binding:"required"
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserStatusReq) Reset()         { *m = SetUserStatusReq{} }
func (m *SetUserStatusReq) String() string { return proto.CompactTextString(m) }
func (*SetUserStatusReq) ProtoMessage()    {}
func (*SetUserStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{4}
}

func (m *SetUserStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserStatusReq.Unmarshal(m, b)
}
func (m *SetUserStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserStatusReq.Marshal(b, m, deterministic)
}
func (m *SetUserStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserStatusReq.Merge(m, src)
}
func (m *SetUserStatusReq) XXX_Size() int {
	return xxx_messageInfo_SetUserStatusReq.Size(m)
}
func (m *SetUserStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserStatusReq proto.InternalMessageInfo

func (m *SetUserStatusReq) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SetUserStatusReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UserCompanyReq struct {
	AccountID            int32    `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCompanyReq) Reset()         { *m = UserCompanyReq{} }
func (m *UserCompanyReq) String() string { return proto.CompactTextString(m) }
func (*UserCompanyReq) ProtoMessage()    {}
func (*UserCompanyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{5}
}

func (m *UserCompanyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCompanyReq.Unmarshal(m, b)
}
func (m *UserCompanyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCompanyReq.Marshal(b, m, deterministic)
}
func (m *UserCompanyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCompanyReq.Merge(m, src)
}
func (m *UserCompanyReq) XXX_Size() int {
	return xxx_messageInfo_UserCompanyReq.Size(m)
}
func (m *UserCompanyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCompanyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCompanyReq proto.InternalMessageInfo

func (m *UserCompanyReq) GetAccountID() int32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

type InitRbacReq struct {
	AccountID            int32    `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	CompanyID            int32    `protobuf:"varint,2,opt,name=companyID,proto3" json:"companyID,omitempty"`
	PermissionIDs        []int32  `protobuf:"varint,3,rep,packed,name=permissionIDs,proto3" json:"permissionIDs,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	NickName             string   `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	RealName             string   `protobuf:"bytes,6,opt,name=realName,proto3" json:"realName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRbacReq) Reset()         { *m = InitRbacReq{} }
func (m *InitRbacReq) String() string { return proto.CompactTextString(m) }
func (*InitRbacReq) ProtoMessage()    {}
func (*InitRbacReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{6}
}

func (m *InitRbacReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRbacReq.Unmarshal(m, b)
}
func (m *InitRbacReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRbacReq.Marshal(b, m, deterministic)
}
func (m *InitRbacReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRbacReq.Merge(m, src)
}
func (m *InitRbacReq) XXX_Size() int {
	return xxx_messageInfo_InitRbacReq.Size(m)
}
func (m *InitRbacReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRbacReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitRbacReq proto.InternalMessageInfo

func (m *InitRbacReq) GetAccountID() int32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *InitRbacReq) GetCompanyID() int32 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *InitRbacReq) GetPermissionIDs() []int32 {
	if m != nil {
		return m.PermissionIDs
	}
	return nil
}

func (m *InitRbacReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *InitRbacReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *InitRbacReq) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

type UserPermissionData struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPermissionData) Reset()         { *m = UserPermissionData{} }
func (m *UserPermissionData) String() string { return proto.CompactTextString(m) }
func (*UserPermissionData) ProtoMessage()    {}
func (*UserPermissionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{7}
}

func (m *UserPermissionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPermissionData.Unmarshal(m, b)
}
func (m *UserPermissionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPermissionData.Marshal(b, m, deterministic)
}
func (m *UserPermissionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPermissionData.Merge(m, src)
}
func (m *UserPermissionData) XXX_Size() int {
	return xxx_messageInfo_UserPermissionData.Size(m)
}
func (m *UserPermissionData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPermissionData.DiscardUnknown(m)
}

var xxx_messageInfo_UserPermissionData proto.InternalMessageInfo

func (m *UserPermissionData) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type UserPermissionRes struct {
	Code                 int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserPermissionData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserPermissionRes) Reset()         { *m = UserPermissionRes{} }
func (m *UserPermissionRes) String() string { return proto.CompactTextString(m) }
func (*UserPermissionRes) ProtoMessage()    {}
func (*UserPermissionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{8}
}

func (m *UserPermissionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPermissionRes.Unmarshal(m, b)
}
func (m *UserPermissionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPermissionRes.Marshal(b, m, deterministic)
}
func (m *UserPermissionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPermissionRes.Merge(m, src)
}
func (m *UserPermissionRes) XXX_Size() int {
	return xxx_messageInfo_UserPermissionRes.Size(m)
}
func (m *UserPermissionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPermissionRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserPermissionRes proto.InternalMessageInfo

func (m *UserPermissionRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserPermissionRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserPermissionRes) GetData() *UserPermissionData {
	if m != nil {
		return m.Data
	}
	return nil
}

type JoinReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReq) Reset()         { *m = JoinReq{} }
func (m *JoinReq) String() string { return proto.CompactTextString(m) }
func (*JoinReq) ProtoMessage()    {}
func (*JoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{9}
}

func (m *JoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReq.Unmarshal(m, b)
}
func (m *JoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReq.Marshal(b, m, deterministic)
}
func (m *JoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReq.Merge(m, src)
}
func (m *JoinReq) XXX_Size() int {
	return xxx_messageInfo_JoinReq.Size(m)
}
func (m *JoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReq proto.InternalMessageInfo

func (m *JoinReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SetUserRoleReq struct {
	//@inject_tag: json:"uid"
	UID int32 `protobuf:"varint,1,opt,name=UID,proto3" json:"uid"`
	//@inject_tag: json:"role_ids" binding:"required"
	RoleIDs              []int32  `protobuf:"varint,2,rep,packed,name=roleIDs,proto3" json:"role_ids" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserRoleReq) Reset()         { *m = SetUserRoleReq{} }
func (m *SetUserRoleReq) String() string { return proto.CompactTextString(m) }
func (*SetUserRoleReq) ProtoMessage()    {}
func (*SetUserRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{10}
}

func (m *SetUserRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserRoleReq.Unmarshal(m, b)
}
func (m *SetUserRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserRoleReq.Marshal(b, m, deterministic)
}
func (m *SetUserRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserRoleReq.Merge(m, src)
}
func (m *SetUserRoleReq) XXX_Size() int {
	return xxx_messageInfo_SetUserRoleReq.Size(m)
}
func (m *SetUserRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserRoleReq proto.InternalMessageInfo

func (m *SetUserRoleReq) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SetUserRoleReq) GetRoleIDs() []int32 {
	if m != nil {
		return m.RoleIDs
	}
	return nil
}

type UserCompanyData struct {
	//@inject_tag: json:"company_ids"
	CompanyIDs           []int32  `protobuf:"varint,1,rep,packed,name=companyIDs,proto3" json:"company_ids"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCompanyData) Reset()         { *m = UserCompanyData{} }
func (m *UserCompanyData) String() string { return proto.CompactTextString(m) }
func (*UserCompanyData) ProtoMessage()    {}
func (*UserCompanyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{11}
}

func (m *UserCompanyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCompanyData.Unmarshal(m, b)
}
func (m *UserCompanyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCompanyData.Marshal(b, m, deterministic)
}
func (m *UserCompanyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCompanyData.Merge(m, src)
}
func (m *UserCompanyData) XXX_Size() int {
	return xxx_messageInfo_UserCompanyData.Size(m)
}
func (m *UserCompanyData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCompanyData.DiscardUnknown(m)
}

var xxx_messageInfo_UserCompanyData proto.InternalMessageInfo

func (m *UserCompanyData) GetCompanyIDs() []int32 {
	if m != nil {
		return m.CompanyIDs
	}
	return nil
}

type UserCompanyRes struct {
	Code                 int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserCompanyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserCompanyRes) Reset()         { *m = UserCompanyRes{} }
func (m *UserCompanyRes) String() string { return proto.CompactTextString(m) }
func (*UserCompanyRes) ProtoMessage()    {}
func (*UserCompanyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{12}
}

func (m *UserCompanyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCompanyRes.Unmarshal(m, b)
}
func (m *UserCompanyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCompanyRes.Marshal(b, m, deterministic)
}
func (m *UserCompanyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCompanyRes.Merge(m, src)
}
func (m *UserCompanyRes) XXX_Size() int {
	return xxx_messageInfo_UserCompanyRes.Size(m)
}
func (m *UserCompanyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCompanyRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserCompanyRes proto.InternalMessageInfo

func (m *UserCompanyRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserCompanyRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserCompanyRes) GetData() *UserCompanyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginReq struct {
	//@inject_tag: json:"company_id" binding:"required"
	CompanyID int32 `protobuf:"varint,1,opt,name=companyID,proto3" json:"company_id" binding:"required"`
	//@inject_tag: json:"account_id" binding:"required"
	AccountID int32 `protobuf:"varint,2,opt,name=accountID,proto3" json:"account_id" binding:"required"`
	//@inject_tag: json:"client_type" binding:"required"  1:平台，2，公司
	ClientType           int32    `protobuf:"varint,3,opt,name=ClientType,proto3" json:"client_type" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{13}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetCompanyID() int32 {
	if m != nil {
		return m.CompanyID
	}
	return 0
}

func (m *LoginReq) GetAccountID() int32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *LoginReq) GetClientType() int32 {
	if m != nil {
		return m.ClientType
	}
	return 0
}

type LoginData struct {
	//@inject_tag: json:"userInfo"
	UserInfo *UserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo"`
	//@inject_tag: json:"-"
	LoginKey             string   `protobuf:"bytes,2,opt,name=LoginKey,proto3" json:"-"`
	PermissionIDs        []int32  `protobuf:"varint,3,rep,packed,name=permissionIDs,proto3" json:"permissionIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}
func (*LoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{14}
}

func (m *LoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginData.Unmarshal(m, b)
}
func (m *LoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginData.Marshal(b, m, deterministic)
}
func (m *LoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginData.Merge(m, src)
}
func (m *LoginData) XXX_Size() int {
	return xxx_messageInfo_LoginData.Size(m)
}
func (m *LoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginData proto.InternalMessageInfo

func (m *LoginData) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *LoginData) GetLoginKey() string {
	if m != nil {
		return m.LoginKey
	}
	return ""
}

func (m *LoginData) GetPermissionIDs() []int32 {
	if m != nil {
		return m.PermissionIDs
	}
	return nil
}

type LoginRes struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *LoginData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{15}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginRes) GetData() *LoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserInfoData struct {
	//@inject_tag: json:"userInfo"
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoData) Reset()         { *m = UserInfoData{} }
func (m *UserInfoData) String() string { return proto.CompactTextString(m) }
func (*UserInfoData) ProtoMessage()    {}
func (*UserInfoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{16}
}

func (m *UserInfoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoData.Unmarshal(m, b)
}
func (m *UserInfoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoData.Marshal(b, m, deterministic)
}
func (m *UserInfoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoData.Merge(m, src)
}
func (m *UserInfoData) XXX_Size() int {
	return xxx_messageInfo_UserInfoData.Size(m)
}
func (m *UserInfoData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoData.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoData proto.InternalMessageInfo

func (m *UserInfoData) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type UserInfoRes struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserInfoData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserInfoRes) Reset()         { *m = UserInfoRes{} }
func (m *UserInfoRes) String() string { return proto.CompactTextString(m) }
func (*UserInfoRes) ProtoMessage()    {}
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{17}
}

func (m *UserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRes.Unmarshal(m, b)
}
func (m *UserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRes.Marshal(b, m, deterministic)
}
func (m *UserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRes.Merge(m, src)
}
func (m *UserInfoRes) XXX_Size() int {
	return xxx_messageInfo_UserInfoRes.Size(m)
}
func (m *UserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRes proto.InternalMessageInfo

func (m *UserInfoRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserInfoRes) GetData() *UserInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserAddReq struct {
	//@inject_tag: json:"account_id" binding:"required"
	AccountID            int32    `protobuf:"varint,1,opt,name=accountID,proto3" json:"account_id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddReq) Reset()         { *m = UserAddReq{} }
func (m *UserAddReq) String() string { return proto.CompactTextString(m) }
func (*UserAddReq) ProtoMessage()    {}
func (*UserAddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{18}
}

func (m *UserAddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddReq.Unmarshal(m, b)
}
func (m *UserAddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddReq.Marshal(b, m, deterministic)
}
func (m *UserAddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddReq.Merge(m, src)
}
func (m *UserAddReq) XXX_Size() int {
	return xxx_messageInfo_UserAddReq.Size(m)
}
func (m *UserAddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddReq proto.InternalMessageInfo

func (m *UserAddReq) GetAccountID() int32 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

type UserDelReq struct {
	UID                  int32    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDelReq) Reset()         { *m = UserDelReq{} }
func (m *UserDelReq) String() string { return proto.CompactTextString(m) }
func (*UserDelReq) ProtoMessage()    {}
func (*UserDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{19}
}

func (m *UserDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDelReq.Unmarshal(m, b)
}
func (m *UserDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDelReq.Marshal(b, m, deterministic)
}
func (m *UserDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDelReq.Merge(m, src)
}
func (m *UserDelReq) XXX_Size() int {
	return xxx_messageInfo_UserDelReq.Size(m)
}
func (m *UserDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserDelReq proto.InternalMessageInfo

func (m *UserDelReq) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

type UserListReq struct {
	//@inject_tag: form:"role_id"
	RoleID int32 `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty" form:"role_id"`
	//@inject_tag: form:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name"`
	//@inject_tag: form:"status"
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" form:"status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListReq) Reset()         { *m = UserListReq{} }
func (m *UserListReq) String() string { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()    {}
func (*UserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{20}
}

func (m *UserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReq.Unmarshal(m, b)
}
func (m *UserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReq.Marshal(b, m, deterministic)
}
func (m *UserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReq.Merge(m, src)
}
func (m *UserListReq) XXX_Size() int {
	return xxx_messageInfo_UserListReq.Size(m)
}
func (m *UserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReq proto.InternalMessageInfo

func (m *UserListReq) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *UserListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserListReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UserListData struct {
	List                 []*UserInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserListData) Reset()         { *m = UserListData{} }
func (m *UserListData) String() string { return proto.CompactTextString(m) }
func (*UserListData) ProtoMessage()    {}
func (*UserListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{21}
}

func (m *UserListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListData.Unmarshal(m, b)
}
func (m *UserListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListData.Marshal(b, m, deterministic)
}
func (m *UserListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListData.Merge(m, src)
}
func (m *UserListData) XXX_Size() int {
	return xxx_messageInfo_UserListData.Size(m)
}
func (m *UserListData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListData.DiscardUnknown(m)
}

var xxx_messageInfo_UserListData proto.InternalMessageInfo

func (m *UserListData) GetList() []*UserInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type UserListRes struct {
	Code                 int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserListData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserListRes) Reset()         { *m = UserListRes{} }
func (m *UserListRes) String() string { return proto.CompactTextString(m) }
func (*UserListRes) ProtoMessage()    {}
func (*UserListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{22}
}

func (m *UserListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRes.Unmarshal(m, b)
}
func (m *UserListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRes.Marshal(b, m, deterministic)
}
func (m *UserListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRes.Merge(m, src)
}
func (m *UserListRes) XXX_Size() int {
	return xxx_messageInfo_UserListRes.Size(m)
}
func (m *UserListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRes proto.InternalMessageInfo

func (m *UserListRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserListRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserListRes) GetData() *UserListData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserUpdateReq struct {
	//@inject_tag: json:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	//@inject_tag: json:"activity_status"
	ActivityStatus string `protobuf:"bytes,2,opt,name=activityStatus,proto3" json:"activity_status"`
	//@inject_tag: json:"avatar"
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateReq) Reset()         { *m = UserUpdateReq{} }
func (m *UserUpdateReq) String() string { return proto.CompactTextString(m) }
func (*UserUpdateReq) ProtoMessage()    {}
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{23}
}

func (m *UserUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateReq.Unmarshal(m, b)
}
func (m *UserUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateReq.Marshal(b, m, deterministic)
}
func (m *UserUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateReq.Merge(m, src)
}
func (m *UserUpdateReq) XXX_Size() int {
	return xxx_messageInfo_UserUpdateReq.Size(m)
}
func (m *UserUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateReq proto.InternalMessageInfo

func (m *UserUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserUpdateReq) GetActivityStatus() string {
	if m != nil {
		return m.ActivityStatus
	}
	return ""
}

func (m *UserUpdateReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UserQuitReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserQuitReq) Reset()         { *m = UserQuitReq{} }
func (m *UserQuitReq) String() string { return proto.CompactTextString(m) }
func (*UserQuitReq) ProtoMessage()    {}
func (*UserQuitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_354ec31f2f4021bb, []int{24}
}

func (m *UserQuitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQuitReq.Unmarshal(m, b)
}
func (m *UserQuitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQuitReq.Marshal(b, m, deterministic)
}
func (m *UserQuitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQuitReq.Merge(m, src)
}
func (m *UserQuitReq) XXX_Size() int {
	return xxx_messageInfo_UserQuitReq.Size(m)
}
func (m *UserQuitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQuitReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserQuitReq proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserInfo)(nil), "rbac.userInfo")
	proto.RegisterType((*UserRolesReq)(nil), "rbac.userRolesReq")
	proto.RegisterType((*UserRolesData)(nil), "rbac.userRolesData")
	proto.RegisterType((*UserRolesRes)(nil), "rbac.userRolesRes")
	proto.RegisterType((*SetUserStatusReq)(nil), "rbac.setUserStatusReq")
	proto.RegisterType((*UserCompanyReq)(nil), "rbac.UserCompanyReq")
	proto.RegisterType((*InitRbacReq)(nil), "rbac.initRbacReq")
	proto.RegisterType((*UserPermissionData)(nil), "rbac.userPermissionData")
	proto.RegisterType((*UserPermissionRes)(nil), "rbac.userPermissionRes")
	proto.RegisterType((*JoinReq)(nil), "rbac.joinReq")
	proto.RegisterType((*SetUserRoleReq)(nil), "rbac.setUserRoleReq")
	proto.RegisterType((*UserCompanyData)(nil), "rbac.userCompanyData")
	proto.RegisterType((*UserCompanyRes)(nil), "rbac.userCompanyRes")
	proto.RegisterType((*LoginReq)(nil), "rbac.loginReq")
	proto.RegisterType((*LoginData)(nil), "rbac.loginData")
	proto.RegisterType((*LoginRes)(nil), "rbac.loginRes")
	proto.RegisterType((*UserInfoData)(nil), "rbac.UserInfoData")
	proto.RegisterType((*UserInfoRes)(nil), "rbac.userInfoRes")
	proto.RegisterType((*UserAddReq)(nil), "rbac.userAddReq")
	proto.RegisterType((*UserDelReq)(nil), "rbac.userDelReq")
	proto.RegisterType((*UserListReq)(nil), "rbac.userListReq")
	proto.RegisterType((*UserListData)(nil), "rbac.userListData")
	proto.RegisterType((*UserListRes)(nil), "rbac.userListRes")
	proto.RegisterType((*UserUpdateReq)(nil), "rbac.userUpdateReq")
	proto.RegisterType((*UserQuitReq)(nil), "rbac.userQuitReq")
}

func init() { proto.RegisterFile("rbac/user.proto", fileDescriptor_354ec31f2f4021bb) }

var fileDescriptor_354ec31f2f4021bb = []byte{
	// 936 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0x56, 0x12, 0x37, 0x4d, 0x26, 0x97, 0xb4, 0xd9, 0x3b, 0x8a, 0x15, 0x41, 0x55, 0x19, 0xb8,
	0x4b, 0x0b, 0x4a, 0x44, 0x4f, 0x3c, 0x00, 0xf7, 0x72, 0x3d, 0xbf, 0x04, 0x4e, 0x88, 0x73, 0xc9,
	0x0b, 0x88, 0x87, 0xad, 0xb3, 0xad, 0x0c, 0x8e, 0x1d, 0xb2, 0x9b, 0x4a, 0xf9, 0x75, 0xfc, 0x09,
	0x7e, 0x0d, 0xe2, 0x01, 0xcd, 0xce, 0xda, 0xde, 0x4d, 0x2c, 0x5d, 0x10, 0x2f, 0xd1, 0xee, 0xcc,
	0xec, 0xee, 0x7c, 0xf3, 0x7d, 0x99, 0x31, 0x9c, 0xac, 0xef, 0x78, 0x3c, 0xdd, 0x48, 0xb1, 0x9e,
	0xac, 0xd6, 0xb9, 0xca, 0x99, 0x87, 0x86, 0x11, 0x99, 0xef, 0xb8, 0x14, 0x64, 0x1e, 0x7d, 0xf8,
	0xc8, 0xd3, 0x64, 0xc1, 0x95, 0x98, 0x16, 0x0b, 0x72, 0x04, 0x7f, 0x35, 0xa0, 0x83, 0xc7, 0x67,
	0xd9, 0x7d, 0xce, 0x06, 0xd0, 0x9c, 0x85, 0x7e, 0xe3, 0xa2, 0x31, 0x3e, 0x8a, 0x9a, 0xb3, 0x90,
	0x7d, 0x06, 0xdd, 0x38, 0x5f, 0xae, 0x78, 0xb6, 0x9d, 0x85, 0x7e, 0x13, 0xcd, 0x37, 0xc7, 0x7f,
	0xdf, 0x78, 0xa3, 0xe6, 0xb8, 0x11, 0x55, 0x1e, 0x0c, 0xe3, 0x71, 0x9c, 0x6f, 0x32, 0x35, 0x0b,
	0xfd, 0xd6, 0x4e, 0x58, 0xe9, 0x61, 0x0c, 0xbc, 0x8c, 0x2f, 0x85, 0xef, 0x5d, 0x34, 0xc6, 0xdd,
	0x48, 0xaf, 0xd9, 0x19, 0xb4, 0xf9, 0x23, 0x57, 0x7c, 0xed, 0x1f, 0x69, 0xab, 0xd9, 0xb1, 0xe7,
	0x30, 0xe0, 0xb1, 0x4a, 0x1e, 0x13, 0xb5, 0xbd, 0x55, 0x5c, 0x6d, 0xa4, 0xdf, 0xd6, 0x59, 0xed,
	0x58, 0xf1, 0xbc, 0x24, 0xff, 0xb1, 0xf6, 0x9b, 0x5d, 0x70, 0x01, 0x4f, 0x10, 0x55, 0x94, 0xa7,
	0x42, 0x46, 0xe2, 0x0f, 0x76, 0x0a, 0xad, 0x4d, 0x09, 0x0d, 0x97, 0xc1, 0x25, 0xf4, 0xcb, 0x88,
	0x90, 0x2b, 0xce, 0x7c, 0x38, 0x5e, 0xe7, 0xa9, 0x98, 0x85, 0xd2, 0x6f, 0x5c, 0xb4, 0xc6, 0x47,
	0x51, 0xb1, 0x0d, 0x7e, 0x75, 0x2e, 0x93, 0x08, 0x24, 0xce, 0x17, 0xc2, 0xdc, 0xa6, 0xd7, 0xf8,
	0xc0, 0x52, 0x3e, 0xe8, 0x22, 0x75, 0x23, 0x5c, 0xb2, 0x17, 0xe0, 0x2d, 0xb8, 0xe2, 0xba, 0x20,
	0xbd, 0xeb, 0xa7, 0x13, 0xa4, 0x64, 0xe2, 0x3c, 0x19, 0xe9, 0x80, 0xe0, 0x15, 0x9c, 0x4a, 0xa1,
	0xe6, 0x52, 0xac, 0x09, 0x54, 0x6d, 0xbe, 0x16, 0xd2, 0xa6, 0x83, 0x74, 0x02, 0x03, 0x3c, 0xfa,
	0x86, 0xd8, 0xc0, 0xb3, 0x1f, 0xd9, 0x74, 0xd0, 0x0d, 0x95, 0x21, 0xf8, 0xb3, 0x01, 0xbd, 0x24,
	0x4b, 0x54, 0x74, 0xc7, 0xe3, 0xf7, 0x46, 0xa3, 0x77, 0x47, 0x01, 0x36, 0xf1, 0x9f, 0x42, 0x7f,
	0x25, 0xd6, 0xcb, 0x44, 0xca, 0x24, 0xcf, 0xb0, 0x70, 0x2d, 0x5d, 0x38, 0xd7, 0x68, 0x71, 0xec,
	0x39, 0x1c, 0x8f, 0xa0, 0x93, 0x25, 0xf1, 0xef, 0x3f, 0xa0, 0x26, 0x88, 0xfd, 0x72, 0x8f, 0xbe,
	0xb5, 0xe0, 0xa9, 0xf6, 0xb5, 0xc9, 0x57, 0xec, 0x83, 0x31, 0x30, 0x2c, 0xe3, 0x8f, 0xe5, 0x23,
	0x9a, 0xbe, 0x42, 0x5d, 0xc8, 0x9d, 0x51, 0x57, 0xf0, 0x00, 0x43, 0x37, 0xf2, 0x70, 0xf6, 0xbe,
	0x70, 0xd8, 0xf3, 0x2b, 0xf6, 0xdc, 0x67, 0x0d, 0x85, 0x1f, 0xc3, 0xf1, 0x6f, 0x79, 0x92, 0x61,
	0x3d, 0xed, 0xeb, 0xbb, 0x74, 0x7d, 0xf0, 0x0a, 0x06, 0x86, 0x61, 0xe4, 0xde, 0xf0, 0x3b, 0xaf,
	0xf8, 0x9d, 0xcf, 0x42, 0x5b, 0x7e, 0x4d, 0x57, 0x7e, 0x5f, 0xc2, 0xc9, 0xa6, 0x62, 0x58, 0x83,
	0x3d, 0x07, 0x28, 0x59, 0x28, 0xe4, 0x6a, 0x59, 0x02, 0x0e, 0x83, 0x8d, 0x2d, 0x8a, 0x43, 0x51,
	0x5f, 0x3a, 0xa8, 0x3f, 0xa8, 0x50, 0x5b, 0x8f, 0x1b, 0xc8, 0xf7, 0xd0, 0x49, 0xf3, 0x07, 0xc2,
	0xec, 0xa8, 0xa4, 0xb1, 0xab, 0x12, 0x47, 0x61, 0xcd, 0x5d, 0x85, 0x9d, 0x03, 0xbc, 0x49, 0x13,
	0x91, 0xa9, 0x9f, 0xb6, 0x2b, 0x41, 0xdd, 0x23, 0xb2, 0x2c, 0xc1, 0x16, 0xba, 0xfa, 0x1d, 0x8d,
	0xfb, 0xaa, 0x6a, 0x56, 0xfa, 0x9d, 0xde, 0xf5, 0xa0, 0xca, 0x11, 0xad, 0x51, 0xd5, 0xcc, 0x46,
	0xd0, 0x79, 0x8b, 0x07, 0xbf, 0x17, 0x5b, 0x03, 0xb1, 0xdc, 0x1f, 0x26, 0xdc, 0x60, 0x5e, 0x42,
	0x3c, 0xb4, 0x7e, 0x9f, 0x38, 0xf5, 0x3b, 0xa1, 0xdc, 0xca, 0xf4, 0x4d, 0xe5, 0xbe, 0x81, 0x27,
	0x73, 0x93, 0xe4, 0x7f, 0x05, 0x15, 0xfc, 0x02, 0xbd, 0xd2, 0x7a, 0x70, 0x56, 0xcf, 0x9d, 0xac,
	0x18, 0x5d, 0x6e, 0xa7, 0x60, 0x12, 0xbb, 0x02, 0xc0, 0xcb, 0x5f, 0x2f, 0x16, 0xef, 0x6f, 0x23,
	0xe7, 0x14, 0x1b, 0x8a, 0xb4, 0x56, 0xce, 0xc1, 0x3b, 0x4a, 0xf4, 0x6d, 0x22, 0x15, 0x06, 0x9c,
	0x41, 0x9b, 0xe4, 0x6c, 0x62, 0xcc, 0xae, 0xfc, 0xd7, 0x36, 0xdd, 0x99, 0x60, 0x3a, 0x5d, 0x8b,
	0xfa, 0x85, 0xe9, 0x74, 0xd7, 0xd4, 0x86, 0xf1, 0x4a, 0x5d, 0xb7, 0x00, 0xbc, 0x34, 0x91, 0x4a,
	0xcb, 0x7f, 0xbf, 0x66, 0xda, 0x57, 0xd4, 0x8b, 0xd2, 0xf8, 0x5f, 0xf5, 0xb2, 0x9f, 0x36, 0xf5,
	0x8a, 0x69, 0x84, 0xcc, 0x57, 0x38, 0x4f, 0xcd, 0x7f, 0xdf, 0xf4, 0xa0, 0x0a, 0xcd, 0xfe, 0x24,
	0xa3, 0x97, 0x6a, 0x26, 0x99, 0xe9, 0x92, 0x2d, 0xbb, 0x4b, 0x06, 0x7d, 0x42, 0xf0, 0x6e, 0x93,
	0x60, 0x21, 0xaf, 0xff, 0xf1, 0xc0, 0xc3, 0x3d, 0x9b, 0x42, 0x67, 0x66, 0xda, 0x38, 0x1b, 0x52,
	0x8a, 0x56, 0x5b, 0x1f, 0x9d, 0x92, 0x69, 0x21, 0xee, 0xf9, 0x26, 0xd5, 0xd8, 0x2f, 0xa1, 0xf5,
	0x7a, 0xb1, 0x60, 0xa7, 0x15, 0x1c, 0x22, 0xba, 0x26, 0xf4, 0x0a, 0x3a, 0x85, 0x3c, 0x58, 0x8f,
	0xbc, 0x62, 0xb9, 0x52, 0xdb, 0xd1, 0x70, 0xa7, 0xc8, 0x42, 0x62, 0xa3, 0xc4, 0xb2, 0xb0, 0xa1,
	0x5b, 0x26, 0xbc, 0x78, 0xcf, 0x84, 0xd1, 0xed, 0x50, 0xa4, 0x42, 0x09, 0x3b, 0x0f, 0x12, 0x51,
	0x4d, 0x1e, 0x5f, 0x41, 0xef, 0xb6, 0xea, 0x9b, 0xec, 0x19, 0x05, 0xb8, 0xad, 0xb4, 0xe6, 0xd8,
	0xd7, 0xd0, 0xbf, 0xb5, 0x07, 0x2a, 0x3b, 0x73, 0x0e, 0x96, 0x53, 0xb6, 0xe6, 0xe8, 0x4b, 0xe8,
	0x16, 0x77, 0x4b, 0xc6, 0x76, 0x66, 0x36, 0x1e, 0xd9, 0xb7, 0x49, 0x36, 0x85, 0x36, 0x69, 0x80,
	0x59, 0x53, 0xbe, 0x54, 0x45, 0xcd, 0x2b, 0x2f, 0xc0, 0xfb, 0x2e, 0x4f, 0x32, 0xd6, 0x27, 0x8f,
	0x19, 0x1d, 0x35, 0x81, 0x9f, 0x83, 0x87, 0xc4, 0xdb, 0xc5, 0x35, 0x42, 0xa8, 0x85, 0xdd, 0xb3,
	0xbe, 0x04, 0x8a, 0x6a, 0xb9, 0x1f, 0x07, 0xa3, 0x67, 0x7b, 0x3d, 0x9d, 0x12, 0x3a, 0xd2, 0xbd,
	0x91, 0x0d, 0xac, 0x96, 0x85, 0xe1, 0xee, 0x5e, 0xde, 0x3c, 0xfd, 0x79, 0x38, 0x99, 0xea, 0x2f,
	0xc7, 0x29, 0x3a, 0xbe, 0xc5, 0x9f, 0xbb, 0xb6, 0x36, 0xbc, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x25, 0xf8, 0xee, 0x21, 0x8d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	InitRbac(ctx context.Context, in *InitRbacReq, opts ...grpc.CallOption) (*DefaultRes, error)
	//  机构k
	Add(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*DefaultRes, error)
	UserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserInfoRes, error)
	List(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListRes, error)
	Delete(ctx context.Context, in *UserDelReq, opts ...grpc.CallOption) (*DefaultRes, error)
	SetUserRole(ctx context.Context, in *SetUserRoleReq, opts ...grpc.CallOption) (*DefaultRes, error)
	SetUserStatus(ctx context.Context, in *SetUserStatusReq, opts ...grpc.CallOption) (*DefaultRes, error)
	UserRoles(ctx context.Context, in *UserRolesReq, opts ...grpc.CallOption) (*UserRolesRes, error)
	// 用户
	Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*DefaultRes, error)
	Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*DefaultRes, error)
	Quit(ctx context.Context, in *UserQuitReq, opts ...grpc.CallOption) (*DefaultRes, error)
	UserCompany(ctx context.Context, in *UserCompanyReq, opts ...grpc.CallOption) (*UserCompanyRes, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) InitRbac(ctx context.Context, in *InitRbacReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/InitRbac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Add(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserInfoRes, error) {
	out := new(UserInfoRes)
	err := c.cc.Invoke(ctx, "/rbac.user/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) List(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListRes, error) {
	out := new(UserListRes)
	err := c.cc.Invoke(ctx, "/rbac.user/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Delete(ctx context.Context, in *UserDelReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetUserRole(ctx context.Context, in *SetUserRoleReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/SetUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SetUserStatus(ctx context.Context, in *SetUserStatusReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/SetUserStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserRoles(ctx context.Context, in *UserRolesReq, opts ...grpc.CallOption) (*UserRolesRes, error) {
	out := new(UserRolesRes)
	err := c.cc.Invoke(ctx, "/rbac.user/UserRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Quit(ctx context.Context, in *UserQuitReq, opts ...grpc.CallOption) (*DefaultRes, error) {
	out := new(DefaultRes)
	err := c.cc.Invoke(ctx, "/rbac.user/Quit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserCompany(ctx context.Context, in *UserCompanyReq, opts ...grpc.CallOption) (*UserCompanyRes, error) {
	out := new(UserCompanyRes)
	err := c.cc.Invoke(ctx, "/rbac.user/UserCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/rbac.user/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	InitRbac(context.Context, *InitRbacReq) (*DefaultRes, error)
	//  机构k
	Add(context.Context, *UserAddReq) (*DefaultRes, error)
	UserInfo(context.Context, *Empty) (*UserInfoRes, error)
	List(context.Context, *UserListReq) (*UserListRes, error)
	Delete(context.Context, *UserDelReq) (*DefaultRes, error)
	SetUserRole(context.Context, *SetUserRoleReq) (*DefaultRes, error)
	SetUserStatus(context.Context, *SetUserStatusReq) (*DefaultRes, error)
	UserRoles(context.Context, *UserRolesReq) (*UserRolesRes, error)
	// 用户
	Update(context.Context, *UserUpdateReq) (*DefaultRes, error)
	Join(context.Context, *JoinReq) (*DefaultRes, error)
	Quit(context.Context, *UserQuitReq) (*DefaultRes, error)
	UserCompany(context.Context, *UserCompanyReq) (*UserCompanyRes, error)
	Login(context.Context, *LoginReq) (*LoginRes, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) InitRbac(ctx context.Context, req *InitRbacReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitRbac not implemented")
}
func (*UnimplementedUserServer) Add(ctx context.Context, req *UserAddReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUserServer) UserInfo(ctx context.Context, req *Empty) (*UserInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedUserServer) List(ctx context.Context, req *UserListReq) (*UserListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUserServer) Delete(ctx context.Context, req *UserDelReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUserServer) SetUserRole(ctx context.Context, req *SetUserRoleReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserRole not implemented")
}
func (*UnimplementedUserServer) SetUserStatus(ctx context.Context, req *SetUserStatusReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserStatus not implemented")
}
func (*UnimplementedUserServer) UserRoles(ctx context.Context, req *UserRolesReq) (*UserRolesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRoles not implemented")
}
func (*UnimplementedUserServer) Update(ctx context.Context, req *UserUpdateReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServer) Join(ctx context.Context, req *JoinReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedUserServer) Quit(ctx context.Context, req *UserQuitReq) (*DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quit not implemented")
}
func (*UnimplementedUserServer) UserCompany(ctx context.Context, req *UserCompanyReq) (*UserCompanyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCompany not implemented")
}
func (*UnimplementedUserServer) Login(ctx context.Context, req *LoginReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_InitRbac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRbacReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).InitRbac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/InitRbac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).InitRbac(ctx, req.(*InitRbacReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Add(ctx, req.(*UserAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).List(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Delete(ctx, req.(*UserDelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/SetUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetUserRole(ctx, req.(*SetUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SetUserStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SetUserStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/SetUserStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SetUserStatus(ctx, req.(*SetUserStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/UserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserRoles(ctx, req.(*UserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Update(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Join(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserQuitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/Quit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Quit(ctx, req.(*UserQuitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCompanyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/UserCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserCompany(ctx, req.(*UserCompanyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rbac.user/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rbac.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitRbac",
			Handler:    _User_InitRbac_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _User_Add_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _User_UserInfo_Handler,
		},
		{
			MethodName: "List",
			Handler:    _User_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _User_Delete_Handler,
		},
		{
			MethodName: "SetUserRole",
			Handler:    _User_SetUserRole_Handler,
		},
		{
			MethodName: "SetUserStatus",
			Handler:    _User_SetUserStatus_Handler,
		},
		{
			MethodName: "UserRoles",
			Handler:    _User_UserRoles_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _User_Update_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _User_Join_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _User_Quit_Handler,
		},
		{
			MethodName: "UserCompany",
			Handler:    _User_UserCompany_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rbac/user.proto",
}
